### ISSUE TITLE
pkg/tcp/textproto.String: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/go2rtc#102]
```
8:07:36.448 INF [srtp] listen addr=:8443
18:07:38.782 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:183 > error=EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5c40a0]
goroutine 4 [running]:
net/url.(*URL).String(0x0)
 net/url/url.go:800 +0x40
github.com/AlexxIT/go2rtc/pkg/tcp.(*Request).String(0xc000210050)
 github.com/AlexxIT/go2rtc/pkg/tcp/textproto.go:96 +0x3d
github.com/AlexxIT/go2rtc/pkg/tcp.(*Request).Write(0xa9dac0?, {0xc51c40, 0xc00000e010})
 github.com/AlexxIT/go2rtc/pkg/tcp/textproto.go:108 +0x25
github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Request(0xc0002000e0, 0xc000210050)
 github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:172 +0x3fe
github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Teardown(...)
 github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:456
github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Close(0xc0002000e0)
 github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:463 +0x76
github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler({0xc5a430?, 0xc00000e010})
```

**Comment by maxi1134** [comment]
Any update on this? It started happening on my instance;

```
2022/11/29 03:59:07 http: panic serving 192.168.0.15:50044: runtime error: invalid memory address or nil pointer dereference
goroutine 1222 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1825 +0xbf
panic({0xa9fb60, 0x103f5f0})
        runtime/panic.go:844 +0x258
github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).GetMedias(0xc0000b5880)
        github.com/AlexxIT/go2rtc/cmd/streams/producer.go:58 +0x186
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc0001ca400, {0xc5ca60?, 0xc001692770})
        github.com/AlexxIT/go2rtc/cmd/streams/stream.go:66 +0x3ff
github.com/AlexxIT/go2rtc/cmd/webrtc.ExchangeSDP(0xc0001ca400, {0xc0019af000, 0x16e6}, {0xc000bfa441, 0x31})
        github.com/AlexxIT/go2rtc/cmd/webrtc/webrtc.go:195 +0x2b4
github.com/AlexxIT/go2rtc/cmd/hass.initAPI.func3({0xc5d810, 0xc0000fa0e0}, 0xc000e52700)
        github.com/AlexxIT/go2rtc/cmd/hass/api.go:82 +0x2e5
net/http.HandlerFunc.ServeHTTP(0x72?, {0xc5d810?, 0xc0000fa0e0?}, 0xc0014b8f80?)
        net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0?, {0xc5d810, 0xc0000fa0e0}, 0xc000e52700)
        net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc5bc70?}, {0xc5d810, 0xc0000fa0e0}, 0xc000e52700)
        net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc001056000, {0xc5de38, 0xc0001160c0})
        net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
        net/http/server.go:3071 +0x4db
```
