### ISSUE TITLE
cmd/streams/producer.GetMedias: invalid memory address

### ISSUE THREAD

**Issue by calisro** [AlexxIT/go2rtc#111]
```
19:15:32.216 DBG github.com/AlexxIT/go2rtc/cmd/streams/producer.go:125 > error="dial tcp xxxx:554: i/o timeout"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1f9bd8]
goroutine 2105 [running]:
github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).GetMedias(0x4000280580)
	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:58 +0x1a8
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0x4000254900, {0x7f0bb0?, 0x40002011e0})
	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:66 +0x3d8
github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler.func1({0x6034e0?, 0x7eb5e8?})
	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:154 +0x274
github.com/AlexxIT/go2rtc/pkg/streamer.(*Element).Fire(...)
	github.com/AlexxIT/go2rtc/pkg/streamer/streamer.go:27
github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Accept(0x40002011e0)
	github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:539 +0x9b4
github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler({0x7f60c0?, 0x40000c4a10})
	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:184 +0x328
created by github.com/AlexxIT/go2rtc/cmd/rtsp.Init.func1
	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:55 +0x34
rtsp://127.0.0.1:8554/backyard?audio: Invalid data found when processing input
```

**Comment by AlexxIT** [comment]
Same:

```
14:35:09.960 DBG cmd\streams\producer.go:125 > error="dial tcp 192.168.1.123:554: i/o timeout"
14:35:11.483 DBG [webrtc] new consumer url=dahua1
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x7ff7d6927524]

goroutine 278 [running]:
github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).GetMedias(0x400016d170)
        .../go2rtc/cmd/streams/producer.go:58 +0x1c4
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0x40001bca40, {0x7ff7d6f567e0?, 0x40001a4000})
        .../go2rtc/cmd/streams/stream.go:70 +0x4e0
github.com/AlexxIT/go2rtc/cmd/webrtc.asyncHandler(0x400082c0a0, 0x4000042820)
        .../go2rtc/cmd/webrtc/webrtc.go:114 +0x404
github.com/AlexxIT/go2rtc/cmd/api.apiWS.func2()
        .../go2rtc/cmd/api/ws.go:88 +0x3c
created by github.com/AlexxIT/go2rtc/cmd/api.apiWS
        .../go2rtc/cmd/api/ws.go:87 +0x310
```

**Comment by gofaster** [comment]
Panic when source is temporarily offline.  ` go2rtc version 0.1-rc.6 linux/arm
`
```
Jan 04 20:28:29 rpi4b-1 go2rtc[289]: 01:28:29.680 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:202 > error=EOF
Jan 05 00:13:01 rpi4b-1 go2rtc[289]: 05:13:01.332 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:105 > error=EOF
Jan 05 16:13:01 rpi4b-1 go2rtc[289]: 21:13:01.575 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:105 > error=EOF
Jan 05 16:13:21 rpi4b-1 go2rtc[289]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 05 16:13:21 rpi4b-1 go2rtc[289]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x221c44]
Jan 05 16:13:21 rpi4b-1 go2rtc[289]: goroutine 4321 [running]:
Jan 05 16:13:21 rpi4b-1 go2rtc[289]: github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).GetMedias(0x31c2aa0)
Jan 05 16:13:21 rpi4b-1 go2rtc[289]:         github.com/AlexxIT/go2rtc/cmd/streams/producer.go:58 +0x1c8
Jan 05 16:13:21 rpi4b-1 go2rtc[289]: github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0x31c01e0, {0x8327e4, 0x3284460})
Jan 05 16:13:21 rpi4b-1 go2rtc[289]:         github.com/AlexxIT/go2rtc/cmd/streams/stream.go:70 +0x4e0
Jan 05 16:13:21 rpi4b-1 go2rtc[289]: github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler.func1({0x6a31e0, 0x82f2b4})
Jan 05 16:13:21 rpi4b-1 go2rtc[289]:         github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:166 +0x2f8
Jan 05 16:13:21 rpi4b-1 go2rtc[289]: github.com/AlexxIT/go2rtc/pkg/streamer.(*Element).Fire(...)
Jan 05 16:13:21 rpi4b-1 go2rtc[289]:         github.com/AlexxIT/go2rtc/pkg/streamer/streamer.go:27
Jan 05 16:13:21 rpi4b-1 go2rtc[289]: github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Accept(0x3284460)
Jan 05 16:13:21 rpi4b-1 go2rtc[289]:         github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:558 +0xca8
Jan 05 16:13:21 rpi4b-1 go2rtc[289]: github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler(0x3284460)
Jan 05 16:13:21 rpi4b-1 go2rtc[289]:         github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:201 +0x1d0
Jan 05 16:13:21 rpi4b-1 go2rtc[289]: created by github.com/AlexxIT/go2rtc/cmd/rtsp.Init.func1
Jan 05 16:13:21 rpi4b-1 go2rtc[289]:         github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:63 +0x34
Jan 05 16:13:21 rpi4b-1 systemd[1]: go2rtc.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 05 16:13:21 rpi4b-1 systemd[1]: go2rtc.service: Failed with result 'exit-code'.
Jan 05 16:13:21 rpi4b-1 systemd[1]: go2rtc.service: Consumed 3h 53min 28.162s CPU time.
```

**Comment by AlexxIT** [comment]
Fixed in https://github.com/AlexxIT/go2rtc/releases/tag/v0.1-rc.7
