### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ningnao** [AlexxIT/go2rtc#1261]
version: master(a4885c2c3abce58074d04878bba0d72105642a9b)

I frequently add and delete streams by calling the '/api/streams' endpoint
go2rtc randomly throws these errors
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x6bc081]

goroutine 1964 [running]:
bufio.(*Writer).Write(0xc000daeb80, {0xc000606000?, 0xc0004d4808?, 0xc00010c120?})
	C:/Program Files/Go/src/bufio/bufio.go:679 +0xe1
net/http.(*response).write(0xc00062a000, 0x1298, {0xc000606000, 0x1298, 0x162c}, {0x0, 0x0})
	C:/Program Files/Go/src/net/http/server.go:1653 +0x2fe
net/http.(*response).Write(0x162c?, {0xc000606000?, 0x0?, 0xc000606000?})
	C:/Program Files/Go/src/net/http/server.go:1611 +0x2a
github.com/AlexxIT/go2rtc/pkg/core.(*WriteBuffer).Write(0xc0003a6080, {0xc000606000?, 0xc000a94e10?, 0xc0005cded8?})
	G:/go2rtc/pkg/core/writebuffer.go:33 +0x92
github.com/AlexxIT/go2rtc/pkg/mp4.(*Consumer).AddTrack.func2(0xc0009ee000?)
	G:/go2rtc/pkg/mp4/consumer.go:106 +0xae
github.com/AlexxIT/go2rtc/pkg/mp4.(*Consumer).AddTrack.RTPDepay.func4(0xc0001a3680)
	G:/go2rtc/pkg/h265/rtp.go:87 +0x8c6
github.com/AlexxIT/go2rtc/pkg/core.NewSender.func2(0xc000bde000?)
	G:/go2rtc/pkg/core/track.go:112 +0x1b
github.com/AlexxIT/go2rtc/pkg/core.(*Sender).Start.func1()
	G:/go2rtc/pkg/core/track.go:144 +0x47
created by github.com/AlexxIT/go2rtc/pkg/core.(*Sender).Start in goroutine 34
	G:/go2rtc/pkg/core/track.go:142 +0x10a
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x6bc081]

goroutine 1429 [running]:
bufio.(*Writer).Write(0xc0004ac0c0, {0xc0016af000?, 0xc000314808?, 0xc0006687c0?})
	C:/Program Files/Go/src/bufio/bufio.go:679 +0xe1
net/http.(*response).write(0xc000123260, 0xc5c, {0xc0016af000, 0xc5c, 0xff0}, {0x0, 0x0})
	C:/Program Files/Go/src/net/http/server.go:1653 +0x2fe
net/http.(*response).Write(0xff0?, {0xc0016af000?, 0x0?, 0xc0016af000?})
	C:/Program Files/Go/src/net/http/server.go:1611 +0x2a
github.com/AlexxIT/go2rtc/pkg/core.(*WriteBuffer).Write(0xc000081240, {0xc0016af000?, 0xc000eab560?, 0xc000ba9ee0?})
	G:/go2rtc/pkg/core/writebuffer.go:33 +0x92
github.com/AlexxIT/go2rtc/pkg/mp4.(*Consumer).AddTrack.func1(0xc000410cc0?)
	G:/go2rtc/pkg/mp4/consumer.go:82 +0xae
github.com/AlexxIT/go2rtc/pkg/h264.RTPDepay.func1(0xc000eab4d0)
	G:/go2rtc/pkg/h264/rtp.go:100 +0x39b
github.com/AlexxIT/go2rtc/pkg/core.NewSender.func2(0xc000ba9fd0?)
	G:/go2rtc/pkg/core/track.go:112 +0x1b
github.com/AlexxIT/go2rtc/pkg/core.(*Sender).Start.func1()
	G:/go2rtc/pkg/core/track.go:144 +0x47
created by github.com/AlexxIT/go2rtc/pkg/core.(*Sender).Start in goroutine 29
	G:/go2rtc/pkg/core/track.go:142 +0x10a
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x6bbda5]

goroutine 3603 [running]:
bufio.(*Writer).Flush(0xc00039e3c0)
	C:/Program Files/Go/src/bufio/bufio.go:639 +0x45
net/http.(*response).FlushError(0xc0004ec000)
	C:/Program Files/Go/src/net/http/server.go:1723 +0x36
net/http.(*response).Flush(0x68d?)
	C:/Program Files/Go/src/net/http/server.go:1716 +0x13
github.com/AlexxIT/go2rtc/pkg/core.(*WriteBuffer).Write(0xc00039e400, {0xc000a48700?, 0xc000a07170?, 0xc0026d3ef8?})
	G:/go2rtc/pkg/core/writebuffer.go:37 +0x185
github.com/AlexxIT/go2rtc/pkg/mp4.(*Consumer).AddTrack.func3(0xc00097f8c0?)
	G:/go2rtc/pkg/mp4/consumer.go:127 +0xa5
github.com/AlexxIT/go2rtc/pkg/pcm.FLACEncoder.func1(0xc000897050)
	G:/go2rtc/pkg/pcm/flac.go:149 +0x3f8
github.com/AlexxIT/go2rtc/pkg/core.NewSender.func2(0xc0026d3fd0?)
	G:/go2rtc/pkg/core/track.go:112 +0x1b
github.com/AlexxIT/go2rtc/pkg/core.(*Sender).Start.func1()
	G:/go2rtc/pkg/core/track.go:144 +0x47
created by github.com/AlexxIT/go2rtc/pkg/core.(*Sender).Start in goroutine 41
	G:/go2rtc/pkg/core/track.go:142 +0x10a
```

config
```
streams:
        camera1: rtsp://***:***@192.168.1.141/media/video1
        camera2: rtsp://192.168.1.38:554/ch01.264
```
camera1 sends h265
camera2 sends h264

**Comment by AlexxIT** [comment]
Probably fixed v1.7.0 https://github.com/AlexxIT/go2rtc/commit/2e4e75e386bdaaacbcefa51e399d849ec7534ddc

**Comment by caco3** [comment]
I am having this issue since some weeks (Auto update of the docker container). Before it was working fine.

**Comment by caco3** [comment]
Some more details:
I am using the docker container on my Synlogy NAS and access it through your Homeassistant HACS addon [WebRTC](https://github.com/AlexxIT/WebRTC).

With v1.9.8 it works great, with 1.9.9 I get the following crash as soon as I open the stream on Homeassistant:
```
19:48:11.943 INF go2rtc platform=linux/amd64 revision=fa580c5 version=1.9.9
19:48:11.945 INF config path=/config/go2rtc.yaml
19:48:11.946 INF [rtsp] listen addr=:8554
19:48:11.946 INF [api] listen addr=:1984
19:48:11.951 INF [webrtc] listen addr=:8555
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x978d98]

goroutine 37 [running]:
github.com/pion/ice/v2.(*MultiUDPMuxDefault).RemoveConnByUfrag(0xc0001cf7c0?, {0x0, 0x0})
	github.com/pion/ice/v2@v2.3.37/udp_mux_multi.go:51 +0x18
github.com/pion/ice/v2.(*Agent).removeUfragFromMux(0xc00044e908)
	github.com/pion/ice/v2@v2.3.37/agent.go:914 +0x72
github.com/pion/ice/v2.(*Agent).Restart.func1({0xc00040bf58?, 0xc00040bf30?}, 0xc00044e908)
	github.com/pion/ice/v2@v2.3.37/agent.go:1267 +0x65
github.com/pion/ice/v2.(*Agent).taskLoop(0xc00044e908)
	github.com/pion/ice/v2@v2.3.37/agent.go:246 +0x11a
created by github.com/pion/ice/v2.NewAgent in goroutine 6
	github.com/pion/ice/v2@v2.3.37/agent.go:375 +0xdd9
```

**Comment by AlexxIT** [comment]
@caco3 There's a other issue for this panic

**Comment by caco3** [comment]
is there a way to help to nail it down?

**Comment by AlexxIT** [comment]
Just check latest master version. It has an updated pion library. It may already have this bug fixed there. I don't know.

**Comment by caco3** [comment]
I tried the latest master image from dockerhub, but it still crashes:
```
21:55:46.349 INF go2rtc platform=linux/amd64 revision=f45fef2 version=1.9.9
21:55:46.349 INF config path=/config/go2rtc.yaml
21:55:46.351 INF [rtsp] listen addr=:8554
21:55:46.351 INF [api] listen addr=:1984
21:55:46.355 INF [webrtc] listen addr=:8555
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9a9eb8]

goroutine 49 [running]:
github.com/pion/ice/v4.(*MultiUDPMuxDefault).RemoveConnByUfrag(0xc0001c3680?, {0x0, 0x0})
	github.com/pion/ice/v4@v4.0.9/udp_mux_multi.go:53 +0x18
github.com/pion/ice/v4.(*Agent).removeUfragFromMux(0xc00040e608)
	github.com/pion/ice/v4@v4.0.9/agent.go:908 +0x72
github.com/pion/ice/v4.NewAgent.func2()
	github.com/pion/ice/v4@v4.0.9/agent.go:302 +0x25
github.com/pion/ice/v4/internal/taskloop.(*Loop).runLoop.func1()
	github.com/pion/ice/v4@v4.0.9/internal/taskloop/taskloop.go:50 +0x22
panic({0xc59f20?, 0x13eaab0?})
	runtime/panic.go:792 +0x132
github.com/pion/ice/v4.(*MultiUDPMuxDefault).RemoveConnByUfrag(0xc0001c3680?, {0x0, 0x0})
	github.com/pion/ice/v4@v4.0.9/udp_mux_multi.go:53 +0x18
github.com/pion/ice/v4.(*Agent).removeUfragFromMux(0xc00040e608)
	github.com/pion/ice/v4@v4.0.9/agent.go:908 +0x72
github.com/pion/ice/v4.(*Agent).Restart.func1({0xc00033af58?, 0xc00033af50?})
	github.com/pion/ice/v4@v4.0.9/agent.go:1274 +0x5c
github.com/pion/ice/v4/internal/taskloop.(*Loop).runLoop(0xc0000d8e40, 0xc00033afb8?)
	github.com/pion/ice/v4@v4.0.9/internal/taskloop/taskloop.go:59 +0x84
created by github.com/pion/ice/v4/internal/taskloop.New in goroutine 15
	github.com/pion/ice/v4@v4.0.9/internal/taskloop/taskloop.go:42 +0xf3

```

**Comment by AlexxIT** [comment]
Thank you. Sad to know that the update didn't help.
Unfortunately, I don't get this error. I don't know yet how to repeat it and therefore fix it.
