### ISSUE TITLE
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6033c6]

### ISSUE THREAD

**Issue by NickM-27** [AlexxIT/go2rtc#128]
Getting this crash when a camera is having trouble connecting

```
2022-12-06 20:51:57.116213663  [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6033c6]
2022-12-06 20:51:57.116214513  
2022-12-06 20:51:57.116215333  goroutine 225 [running]:
2022-12-06 20:51:57.116224913  github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).GetMedias(0xc00012c200)
2022-12-06 20:51:57.116226073   github.com/AlexxIT/go2rtc/cmd/streams/producer.go:58 +0x186
2022-12-06 20:51:57.116227173  github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc0001182c0, {0xc843a0?, 0xc0003081a0})
2022-12-06 20:51:57.116228153   github.com/AlexxIT/go2rtc/cmd/streams/stream.go:70 +0x4c5
2022-12-06 20:51:57.116233663  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler.func1({0xa88fa0?, 0xc7ea00?})
2022-12-06 20:51:57.116234663   github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:166 +0x29b
2022-12-06 20:51:57.116239433  github.com/AlexxIT/go2rtc/pkg/streamer.(*Element).Fire(...)
2022-12-06 20:51:57.116244183   github.com/AlexxIT/go2rtc/pkg/streamer/streamer.go:27
2022-12-06 20:51:57.116245283  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Accept(0xc0003081a0)
2022-12-06 20:51:57.116250333   github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:558 +0xbd7
2022-12-06 20:51:57.116254913  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler(0xc0003081a0)
2022-12-06 20:51:57.116259953   github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:201 +0x1a7
2022-12-06 20:51:57.116260923  created by github.com/AlexxIT/go2rtc/cmd/rtsp.Init.func1
2022-12-06 20:51:57.116262813   github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:63 +0x48
```

**Comment by AlexxIT** [comment]
#111
