### ISSUE TITLE
MSE/ H265 Console Errors/ Video doesn't load

### ISSUE THREAD

**Issue by illuzn** [AlexxIT/go2rtc#1302]
# Issue
The MSE stream does not load/ play when using `stream.html?src=Camera&mode=mse` and console errors are generated.

# Console Output
```Text
video-rtc.js:167  Uncaught TypeError: Cannot read properties of undefined (reading 'catch')
    at VideoStream.play (video-rtc.js:167:26)
    at VideoStream.onmse (video-rtc.js:430:14)
    at VideoStream.onopen (video-rtc.js:355:18)
    at VideoStream.onopen (video-stream.js:68:30)
    at WebSocket.<anonymous> (video-rtc.js:304:53)
play @ video-rtc.js:167
onmse @ video-rtc.js:430
onopen @ video-rtc.js:355
onopen @ video-stream.js:68
(anonymous) @ video-rtc.js:304

inject.js:55  Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.
value @ inject.js:55
play @ video-rtc.js:167
onmse @ video-rtc.js:430
onopen @ video-rtc.js:355
onopen @ video-stream.js:68
(anonymous) @ video-rtc.js:304

VM42:23 type: video/mp4; codecs="avc1.640029"
VM42:23 type: video/mp4; codecs="avc1.64002A"
VM42:23 type: video/mp4; codecs="avc1.640033"
VM42:23 type: video/mp4; codecs="hvc1.1.6.L153.B0"
VM42:23 type: video/mp4; codecs="mp4a.40.2"
VM42:23 type: video/mp4; codecs="mp4a.40.5"
VM42:23 type: video/mp4; codecs="flac"
VM42:23 type: video/mp4; codecs="opus"

video-rtc.js:344  Uncaught TypeError: this.ondata is not a function
    at WebSocket.<anonymous> (video-rtc.js:344:22)
(anonymous) @ video-rtc.js:344
```

# Stream Info
```json
{
    "producers": [
        {
            "type": "RTSP active producer",
            "url": "rtsp://REDACTED:554/ch06/0",
            "remote_addr": "REDACTED:554",
            "user_agent": "go2rtc/1.9.2",
            "sdp": "v=0\r\no=- 682945877 682945877 IN IP4 REDACTED\r\ns=RTSP Session with audiobackchannel\r\nc=IN IP4 REDACTED\r\nt=0 0\r\nm=video 0 RTP/AVP 96\r\nc=IN IP4 0.0.0.0\r\nb=AS:5000\r\na=control:trackID=0\r\na=rtpmap:96 H265/90000\r\na=x-dimensions:1920,1080\r\na=framerate:15\r\na=bitrate:1024\r\na=fmtp:96 profile-space=0;profile-id=1;tier-flag=0;level-id=123;nterop-constraints=B00000000000;sprop-vps=QAEMAf//AWAAAAMAsAAAAwAAAwB7rAk=;sprop-sps=QgEBAWAAAAMAsAAAAwAAAwB7oAPAgBDlja5JMvTcBAQEAg==;sprop-pps=RAHA8vA8kA==\r\na=recvonly\r\n",
            "medias": [
                "video, recvonly, H265"
            ],
            "receivers": [
                "96 H265, bytes=263095616, senders=2"
            ],
            "recv": 265532660
        }
    ],
    "consumers": [
        {
            "type": "MSE/WebSocket active consumer",
            "remote_addr": "REDACTED:44471",
            "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0",
            "medias": [
                "video, sendonly, H264, H265",
                "audio, sendonly, MPEG4-GENERIC, PCMA, PCMU, L16, PCML, OPUS"
            ],
            "senders": [
                "96 H265, bytes=2255908, receivers=1"
            ],
            "send": 2264124
        }
    ]
}
```

# Browser Info
Browser: 127.0.2651.86 (Official build) (64-bit)
Running H265ify (latest commit)

# Other useful information
I am playing locally so there should not be firewall/ NAT issues.

**Comment by illuzn** [comment]
I have just installed Chrome 127.0.6533.89 and it works correctly.

Using `edge://media-internals/` I can see the following logs:

Timestamp|Property|Value 
-- | -- | --
00:00:00.000 | created | "2024-08-09 08:09:53.729063 UTC"
00:00:00.004 | info | "AV1 decoder support: 0, WebMfDecoderCheck: not null, kMediaFoundationClearAV1Support enabled: 1, disable_av1_accelerated_decode_gpu_workaround: 0, av1_hw_decoder_support: 0, vp9_decoder_support: 1"
00:00:00.004 | info | "kForceMFMediaEngineRenderer:No; kMediaFoundationClearPlayback:No; DCompDisabled:No; RemotePlaybackDisabled:Yes; DomainOverride:Uninitialized; CDMAvailable:Yes; MFOverrideEnabled:No; MFClearWorkaround:Enabled;CanUseVidSuperRes:No; IsOnBattery: No; BatteryExclusiveStart:No"
00:00:00.005 | origin_url | "http://REDACTED:1984/"
00:00:00.005 | kFrameUrl | "http://REDACTED:1984/stream.html?src=Backyard_Left&mode=mse"
00:00:00.005 | kFrameTitle | "go2rtc - Stream"
00:00:00.005 | kMediaAutoplayPolicy | "no-user-gesture-required"
00:00:00.005 | autoplay_decision | {"effectively_muted":false,"policy":"no-user-gesture-required","source":"method","was_blocked":false}
00:00:00.005 | url | "blob:http://REDACTED:1984/bca5fa12-dc1f-4c68-a120-d5404d6f1619"
00:00:00.005 | info | "ChunkDemuxer"
00:00:00.005 | kRendererName | "RendererImpl"
00:00:00.006 | renderer_created | {"renderer_engine":"Default","renderer_type":"RendererImpl"}
00:00:00.009 | pipeline_state | "kStarting"

**Comment by illuzn** [comment]
Play also works using `/api/stream.mp4?src=Backyard_Left&mp4=all`

```
"Selected VDAVideoDecoder for video decoding, config: codec: hevc, profile: hevc main, level: not available, alpha_mode: is_opaque, coded size: [1920,1080], visible rect: [0,0,1920,1080], natural size: [1920,1080], has extra data: true, encryption scheme: Unencrypted, rotation: 0°, flipped: 0, color space: {primaries:BT709, transfer:BT709, matrix:BT709, range:FULL}"

```

**Comment by AlexxIT** [comment]
It's hard to say. I don't see any possible causes of the problem. The browser supports H265. The bytes are being transmitted.

**Comment by illuzn** [comment]
Any steps I can use to further diagnose?
Thanks for your time.

**Comment by AlexxIT** [comment]
Once again. MP4 stream works for you and MSE don't?

**Comment by illuzn** [comment]
Yes, neither MSE or WebRTC but the modern mp4 and legacy mp4 links work fine.

**Comment by AlexxIT** [comment]
You can try to share this RTSP stream to me. But only after 25 aug.

**Comment by illuzn** [comment]
Okay no problems.... let me know when you are ready and I will pinhole the direct camera feed and the go2rtc output for you.

Let me know some details where I can privately send those to you when you are ready (and also when you are finished so I can close them).
