### ISSUE TITLE
Wrong profile from Eufy T8400

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/go2rtc#155]
```
Uncaught DOMException: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="avc1.276400,mp4a.40.2"') is unsupported.
    at onmessage.mse (http://192.168.1.168:8123/webrtc/video-rtc.js:391:27)
    at WebSocket.<anonymous> (http://192.168.1.168:8123/webrtc/video-rtc.js:312:41)
onmessage.mse @ video-rtc.js:391
(anonymous) @ video-rtc.js:312
video-rtc.js:315 Uncaught TypeError: this.ondata is not a function
    at WebSocket.<anonymous> (video-rtc.js:315:22)
```

```
v=0
o=- 0 0 IN IP4 127.0.0.1
s=H.264 Video,leco stream
c=IN IP4 0.0.0.0
t=0 0
a=tool:prv
a=control:*
m=video 0 RTP/AVP 96
b=AS:134
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=276400;sprop-parameter-sets=J2QAKq0AzoB4AiflmoCAgPgAAAMACAAAAwDxgYABDzwADLbv/+BQ,KO48sA==
a=control:trackID=0
m=audio 0 RTP/AVP 97
b=AS:131
a=rtpmap:97 MPEG4-GENERIC/16000/1
a=fmtp:97 profile-level-id=1;mode=AAC-hbr;sizelength=13;indexlength=3;indexdeltalength=3; config=1408
a=control:trackID=1
```

**Comment by AlexxIT** [comment]
Fixed in https://github.com/AlexxIT/go2rtc/releases/tag/v0.1-rc.7
