### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gminco** [AlexxIT/go2rtc#193]
I'm not sure what am I doing wrong here, I'm trying to install go2rtc and I keep running into issues:

Fresh install, and I get this: 

```
10:06:12.274 INF go2rtc version 1.0.0 linux/arm64
10:06:12.275 FTL [api] listen error="listen tcp :1984: bind: address already in use"
```

I've checked netstat and I have nothing listening on 1984, so I went ahead and configured a different one on a go2rtc.yaml file:

```
api:
  listen: ":1985"
```

Then it starts, but it crashes, I've tried rebooting the host itself a couple of times, I keep running into the same issue:

```
10:13:58.295 INF go2rtc version 1.0.0 linux/arm64
10:13:58.299 INF [api] listen addr=:1985
10:13:58.300 ERR [rtsp] listen error="listen tcp :8554: bind: address already in use"
10:13:58.308 INF [hass] load stream url="hass:Front Door Cam"
10:13:58.309 INF [hass] load stream url="hass:Basement Cam"
10:13:58.309 INF [hass] load stream url="hass:Deck Cam"
10:13:58.309 INF [hass] load stream url="hass:Backyard Cam"
10:13:58.309 INF [hass] load stream url="hass:East Cam"
10:13:58.315 INF [webrtc] listen addr=:8555
10:13:58.324 WRN github.com/AlexxIT/go2rtc/cmd/srtp/srtp.go:31 > error="listen udp :8443: bind: address already in use"
10:13:58.325 INF [srtp] listen addr=:8443
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x57f548]
goroutine 19 [running]:
github.com/AlexxIT/go2rtc/pkg/srtp.(*Server).Serve(0x4000124000, {0x0?, 0x0})
	github.com/AlexxIT/go2rtc/pkg/srtp/server.go:41 +0x78
github.com/AlexxIT/go2rtc/cmd/srtp.Init.func1()
	github.com/AlexxIT/go2rtc/cmd/srtp/srtp.go:39 +0x88
created by github.com/AlexxIT/go2rtc/cmd/srtp.Init
	github.com/AlexxIT/go2rtc/cmd/srtp/srtp.go:37 +0x278
```

Version of HA:
Home Assistant 2023.1.5
Supervisor 2022.12.1
Operating System 9.4
Frontend 20230110.0 - latest

Thanks!!

**Comment by AlexxIT** [comment]
I think you already have go2rtc on your server.

**Comment by gminco** [comment]
Yup, I just ran into the same conclusion after troubleshooting for a day.
It looks like I previously installed it, then I uninstalled the add-on but left the WebRTC Camera integration.
I got it to work by removing the integration.

Thanks!!
