### ISSUE TITLE
WebSocket is already in CLOSING or CLOSED state.

### ISSUE THREAD

**Issue by maxi1134** [AlexxIT/go2rtc#2]
Hi there,

Thanks for the project!

When trying to use it (With the HA addon install) I get the following browser console error: 

```WebSocket is already in CLOSING or CLOSED state.
(anonymous) @ webrtc.html?url=rtsp%3A%2F%2Fadmin%3AJesus420%40192.168.0.210%2Fh264Preview_01_main:69

The addon logs show:

net/http.serverHandler.ServeHTTP({0xc0002f1ef0?}, {0xafcc30, 0xc00061e380}, 0xc0004c4e00)
	net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc000150000, {0xafcfe8, 0xc000202180})
	net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	net/http/server.go:3071 +0x4db
2022/08/21 15:23:23 http: panic serving 172.30.32.2:54344: runtime error: invalid memory address or nil pointer dereference
goroutine 242 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1825 +0xbf
panic({0x98a500, 0xe33400})
	runtime/panic.go:844 +0x258
github.com/AlexxIT/go2rtc/pkg/webrtc.(*Conn).AddTrack(0xc0000b8600?, 0xa3ce6b?, 0x0?)
	github.com/AlexxIT/go2rtc/pkg/webrtc/streamer.go:18 +0x29
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc0001b0d50, {0xafbfa0?, 0xc0000ca2a0})
	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:66 +0x568
github.com/AlexxIT/go2rtc/cmd/webrtc.offerHandler(0xc000130840, 0xc0000cc280)
	github.com/AlexxIT/go2rtc/cmd/webrtc/webrtc.go:109 +0x428
github.com/AlexxIT/go2rtc/cmd/api.apiWS({0xafcc30, 0xc00021e0e0}, 0xc0004f0100)
	github.com/AlexxIT/go2rtc/cmd/api/api.go:129 +0x1bc
net/http.HandlerFunc.ServeHTTP(0x7f9b8672b568?, {0xafcc30?, 0xc00021e0e0?}, 0x40d2c5?)
	net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0003be0fc?, {0xafcc30, 0xc00021e0e0}, 0xc0004f0100)
	net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc003b07f80?}, {0xafcc30, 0xc00021e0e0}, 0xc0004f0100)
	net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc00064a0a0, {0xafcfe8, 0xc000202180})
	net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	net/http/server.go:3071 +0x4db
2022/08/21 15:25:49 http: panic serving 172.30.32.2:60590: runtime error: invalid memory address or nil pointer dereference
goroutine 218 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1825 +0xbf
panic({0x98a500, 0xe33400})
	runtime/panic.go:844 +0x258
github.com/AlexxIT/go2rtc/pkg/mse.(*Consumer).AddTrack(0xc0000b8600?, 0xa3ce6b?, 0x0?)
	github.com/AlexxIT/go2rtc/pkg/mse/consumer.go:48 +0x29
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc0001b0d50, {0xafbf40?, 0xc0000ca2a0})
	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:66 +0x568
github.com/AlexxIT/go2rtc/cmd/mse.handler(0xc000159d40, 0x94a220?)
	github.com/AlexxIT/go2rtc/cmd/mse/mse.go:31 +0x1ec
github.com/AlexxIT/go2rtc/cmd/api.apiWS({0xafcc30, 0xc00024e000}, 0xc00066cc00)
	github.com/AlexxIT/go2rtc/cmd/api/api.go:129 +0x1bc
net/http.HandlerFunc.ServeHTTP(0x7f9b8672b568?, {0xafcc30?, 0xc00024e000?}, 0x40d2c5?)
	net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00044200c?, {0xafcc30, 0xc00024e000}, 0xc00066cc00)
	net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc000255680?}, {0xafcc30, 0xc00024e000}, 0xc00066cc00)
	net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc00044a5a0, {0xafcfe8, 0xc000202180})
	net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	net/http/server.go:3071 +0x4db
2022/08/21 15:26:22 http: panic serving 172.30.32.2:54718: runtime error: invalid memory address or nil pointer dereference
goroutine 276 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1825 +0xbf
panic({0x98a500, 0xe33400})
	runtime/panic.go:844 +0x258
github.com/AlexxIT/go2rtc/pkg/keyframe.(*Consumer).AddTrack(0xc000314260, 0xa3ce6b?, 0x0)
	github.com/AlexxIT/go2rtc/pkg/keyframe/consumer.go:30 +0x49
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc0001b0d50, {0xafbf10?, 0xc000314260})
	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:66 +0x568
github.com/AlexxIT/go2rtc/cmd/api.frameHandler({0xafcc30, 0xc0001460e0}, 0xc00014e300)
	github.com/AlexxIT/go2rtc/cmd/api/keyframe.go:28 +0x1ef
net/http.HandlerFunc.ServeHTTP(0x7f9b8672b568?, {0xafcc30?, 0xc0001460e0?}, 0x40d2c5?)
	net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc003c56c73?, {0xafcc30, 0xc0001460e0}, 0xc00014e300)
	net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc0003cdd70?}, {0xafcc30, 0xc0001460e0}, 0xc00014e300)
	net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc00044a0a0, {0xafcfe8, 0xc000202180})
	net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	net/http/server.go:3071 +0x4db
2022/08/21 15:26:29 http: panic serving 172.30.32.2:44780: runtime error: invalid memory address or nil pointer dereference
goroutine 169 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1825 +0xbf
panic({0x98a500, 0xe33400})
	runtime/panic.go:844 +0x258
github.com/AlexxIT/go2rtc/pkg/webrtc.(*Conn).AddTrack(0xc0000b8600?, 0xa3ce6b?, 0x0?)
	github.com/AlexxIT/go2rtc/pkg/webrtc/streamer.go:18 +0x29
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc0001b0d50, {0xafbfa0?, 0xc0000ca2a0})
	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:66 +0x568
github.com/AlexxIT/go2rtc/cmd/webrtc.offerHandler(0xc00058c680, 0xc0003142a0)
	github.com/AlexxIT/go2rtc/cmd/webrtc/webrtc.go:109 +0x428
github.com/AlexxIT/go2rtc/cmd/api.apiWS({0xafcc30, 0xc0001461c0}, 0xc0004f1d00)
	github.com/AlexxIT/go2rtc/cmd/api/api.go:129 +0x1bc
net/http.HandlerFunc.ServeHTTP(0x7f9b8672b568?, {0xafcc30?, 0xc0001461c0?}, 0x40d2c5?)
	net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00044200c?, {0xafcc30, 0xc0001461c0}, 0xc0004f1d00)
	net/http/server.go:2462 +0x149
net/http.serverHandler.ServeHTTP({0xc0002e0540?}, {0xafcc30, 0xc0001461c0}, 0xc0004f1d00)
	net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0000c01e0, {0xafcfe8, 0xc000202180})
	net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	net/http/server.go:3071 +0x4db

**Comment by AlexxIT** [comment]
Is the problem remain in the `v0.1-alpha.6`?

**Comment by RomchikL** [comment]
The same error in Alpha 8. HA in docker, go2rtc in windows 10 x64

**Comment by maxi1134** [comment]
Hi there!
It works now! Thanks a lot.
