### ISSUE TITLE
Flv Error

### ISSUE THREAD

**Issue by NickM-27** [AlexxIT/go2rtc#202]
This happened on latest master

```
2023-01-24 10:25:09.182149119   net/http/internal/chunked.go:48 +0x28
2023-01-24 10:25:09.182153629  net/http/internal.(*chunkedReader).Read(0xc000116930, {0xc0003f0000?, 0xc000296a98?, 0xc000296af8?})
2023-01-24 10:25:09.182156079   net/http/internal/chunked.go:98 +0x156
2023-01-24 10:25:09.182162829  net/http.(*body).readLocked(0xc0001d6040, {0xc0003f0000?, 0xc000296b40?, 0x5672e5?})
2023-01-24 10:25:09.182165600   net/http/transfer.go:846 +0x3c
2023-01-24 10:25:09.182172680  net/http.(*body).Read(0x0?, {0xc0003f0000?, 0x0?, 0x0?})
2023-01-24 10:25:09.182175480   net/http/transfer.go:838 +0x125
2023-01-24 10:25:09.182180360  net/http.(*bodyEOFSignal).Read(0xc0001d60c0, {0xc0003f0000, 0x10000, 0x10000})
2023-01-24 10:25:09.182183130   net/http/transport.go:2774 +0x142
2023-01-24 10:25:09.182189740  net/http.(*cancelTimerBody).Read(0xc000034080, {0xc0003f0000?, 0x204?, 0x204?})
2023-01-24 10:25:09.182192520   net/http/client.go:954 +0x33
2023-01-24 10:25:09.182198100  bufio.(*Reader).Read(0xc0002b2d80, {0xc0000d0500, 0xb, 0x0?})
2023-01-24 10:25:09.182200940   bufio/bufio.go:237 +0x1bb
2023-01-24 10:25:09.182207640  io.ReadAtLeast({0xc8f140, 0xc0002b2d80}, {0xc0000d0500, 0xb, 0x100}, 0xb)
2023-01-24 10:25:09.182210360   io/io.go:332 +0x9a
2023-01-24 10:25:09.182212750  io.ReadFull(...)
2023-01-24 10:25:09.182215910   io/io.go:351
2023-01-24 10:25:09.182221210  github.com/AlexxIT/go2rtc/pkg/httpflv.ReadTag({0xc8f140?, 0xc0002b2d80?}, {0xc0000d0500?, 0x100?, 0x100?})
2023-01-24 10:25:09.182224050   github.com/AlexxIT/go2rtc/pkg/httpflv/flvio.go:13 +0x9f
2023-01-24 10:25:09.182226560  github.com/AlexxIT/go2rtc/pkg/httpflv.(*Conn).ReadPacket(0xc0001d6100)
2023-01-24 10:25:09.182229911   github.com/AlexxIT/go2rtc/pkg/httpflv/httpflv.go:144 +0x8b
2023-01-24 10:25:09.182232661  github.com/AlexxIT/go2rtc/pkg/rtmp.(*Client).Handle(0xc0001c9d50)
2023-01-24 10:25:09.182235501   github.com/AlexxIT/go2rtc/pkg/rtmp/client.go:134 +0x132
2023-01-24 10:25:09.182236031  github.com/AlexxIT/go2rtc/pkg/rtmp.(*Client).Start(0x10a68e0?)
2023-01-24 10:25:09.182238471   github.com/AlexxIT/go2rtc/pkg/rtmp/streamer.go:24 +0x19
2023-01-24 10:25:09.182243391  github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).worker(0xc000198360, {0xc95aa0?, 0xc0001c9d50?}, 0x1)
2023-01-24 10:25:09.182245911   github.com/AlexxIT/go2rtc/cmd/streams/producer.go:123 +0x35
2023-01-24 10:25:09.182248401  created by github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).start
2023-01-24 10:25:09.182251171   github.com/AlexxIT/go2rtc/cmd/streams/producer.go:119 +0x1be
2023-01-24 10:25:09.182251561  
2023-01-24 10:25:09.182254251  goroutine 212 [sleep]:
2023-01-24 10:25:09.182256611  time.Sleep(0x5d21dba00)
2023-01-24 10:25:09.182259031   runtime/time.go:195 +0x135
2023-01-24 10:25:09.182261591  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).keepalive(0xc00022e5a0)
2023-01-24 10:25:09.182264131   github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:818 +0x70
2023-01-24 10:25:09.182266881  created by github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Handle
2023-01-24 10:25:09.182270831   github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:712 +0x2f3
2023-01-24 10:25:09.182271251  
2023-01-24 10:25:09.182271651  goroutine 214 [sleep]:
2023-01-24 10:25:09.182274521  time.Sleep(0x5d21dba00)
2023-01-24 10:25:09.182276981   runtime/time.go:195 +0x135
2023-01-24 10:25:09.182279541  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).keepalive(0xc00022e3c0)
2023-01-24 10:25:09.182280041   github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:818 +0x70
2023-01-24 10:25:09.182282831  created by github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Handle
2023-01-24 10:25:09.182285331   github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:712 +0x2f3
2023-01-24 10:25:09.182287941  
2023-01-24 10:25:09.182288361  goroutine 157 [sleep]:
2023-01-24 10:25:09.182290692  time.Sleep(0x5d21dba00)
2023-01-24 10:25:09.182293092   runtime/time.go:195 +0x135
2023-01-24 10:25:09.182295612  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).keepalive(0xc00022ea50)
2023-01-24 10:25:09.182298842   github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:818 +0x70
2023-01-24 10:25:09.182299362  created by github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Handle
2023-01-24 10:25:09.182301852   github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:712 +0x2f3
2023-01-24 10:25:09.182304472  
2023-01-24 10:25:09.182304892  goroutine 159 [sleep]:
2023-01-24 10:25:09.182307232  time.Sleep(0x5d21dba00)
2023-01-24 10:25:09.182310022   runtime/time.go:195 +0x135
2023-01-24 10:25:09.182312522  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).keepalive(0xc00022e4b0)
2023-01-24 10:25:09.182314972   github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:818 +0x70
2023-01-24 10:25:09.182315492  created by github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Handle
2023-01-24 10:25:09.182318162   github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:712 +0x2f3
```

**Comment by AlexxIT** [comment]
Several initial lines are missing

**Comment by NickM-27** [comment]
I'll see if it happens again, unfortunately unraids logs retention are rather short

**Comment by AlexxIT** [comment]
Please reopen issue if it still relevant.
