### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bagobones** [AlexxIT/go2rtc#259]
go2rtc version 1.1.2 linux/amd64 (stand alone docker from master)

Caused this error while trying to stress test the system, I had about 40 webrtc streams running ( several tabs of stream.html running) and one of the cameras errored out. and caused the crash.
```
2:29:40.907 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:kitchen#audio=aac#audio=opus
12:29:46.088 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:kitchen#audio=aac#audio=opus
12:29:49.965 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:132 > error=EOF url=rtsp://tapo_admin:*****************@192.168.103.25/stream1
12:29:51.279 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:kitchen#audio=aac#audio=opus
12:29:56.452 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:kitchen#audio=aac#audio=opus
12:30:03.612 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:kitchen#audio=aac#audio=opus
12:30:24.990 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:kitchen#audio=aac#audio=opus
12:30:30.173 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:132 > error="read tcp 192.168.102.30:37348->192.168.103.7:554: i/o timeout" url=rtsp://admin:***************@192.168.103.7/live
12:30:30.517 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:52 > error="exec: exit status 1" url=ffmpeg:kitchen#audio=aac#audio=opus
12:30:31.060 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:132 > error="read tcp 192.168.102.30:41374->192.168.103.25:554: i/o timeout" url=rtsp://tapo_admin:**********@192.168.103.25/stream1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7a1e7e]
goroutine 10946 [running]:
github.com/AlexxIT/go2rtc/pkg/streamer.(*Track).GetSink(0x0, 0xc00a95a000)
	github.com/AlexxIT/go2rtc/pkg/streamer/track.go:70 +0x1e
github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).reconnect(0xc0000f0360, 0x1)
	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:172 +0x5ee
github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).worker(0xc0000f0360, {0xca0fc0?, 0xc003d20000?}, 0x1)
	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:135 +0x15b
created by github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).reconnect
	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:179 +0x42c
```

```
config:

api:
  listen: ":2984"
rtsp:
  listen: ":9554"
srtp:
  listen: ":9443"
webrtc:
  listen: ":9555"
  
log:
  level: "info"

streams:
  kitchen: #Wyze v3 with beta RTSP firmware
    - rtsp://admin:*********@192.168.103.7/live
    - "ffmpeg:kitchen#audio=aac#audio=opus"
  basement_hall: #tp-link tapo C100
    - rtsp://tapo_admin:*********@192.168.103.45/stream1
    - "ffmpeg:basement_hall#audio=opus"
  main_hall: #tp-link tapo C100
    - rtsp://tapo_admin:*********@192.168.103.25/stream1
    - "ffmpeg:basement_hall#audio=opus"
```

**Comment by bagobones** [comment]
Still a problem in frigate beta9 when many cameras are configured for restreaming

The wyzecam / kitchen cam is the only one not configured for restream.

The reolink cams are the most recent ones I added back to restream.

At least the watch dog in frigate beta9 seems to recover.

```
go2rtc:
  log:
    rtsp: error
  webrtc:
    candidates:
      - 192.168.102.30:8555
      - stun:8555
  streams:
    doorbell: #Amcrest AD110 use the backchannel option to disable 2way audio
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD2}@192.168.103.8:554#backchannel=0
      - "ffmpeg:doorbell#audio=opus" # transcodes audio to opus for webrtc compatibility
    basement: #iSee Generic Dauha Cam
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.103.4:554
      - "ffmpeg:basement#audio=opus" # transcodes audio to opus for webrtc compatibility
    living_room: #iSee Generic Dauha Cam
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.103.5:554
      - "ffmpeg:living_room#audio=opus" # transcodes audio to opus for webrtc compatibility
    kitchen: #Wyze v3 with beta RTSP firmware
      - rtsp://admin:{FRIGATE_RTSP_PASSWORD}@192.168.103.7/live
      - "ffmpeg:kitchen#audio=aac#audio=opus" # transcodes audio to aac for recording and opus for webrtc compatibility
    basement_hall: #tp-link tapo C100
      - rtsp://tapo_admin:{FRIGATE_RTSP_PASSWORD}@192.168.103.45/stream1
      - "ffmpeg:basement_hall#audio=opus" # transcodes audio to opus for webrtc compatibility
    main_hall: #tp-link tapo C100
      - rtsp://tapo_admin:{FRIGATE_RTSP_PASSWORD}@192.168.103.25/stream1
      - "ffmpeg:main_hall#audio=opus" # transcodes audio to opus for webrtc compatibility
    garage_front: #Reolink RLC-410W firmware v3.0.0.136_20121102
      - http://192.168.103.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}
    backyard: #Reolink RLC-410W firmware v3.0.0.136_20121102
      - http://192.168.103.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password={FRIGATE_RTSP_PASSWORD}


```


```
2023-03-10 09:29:50.372752053  [INFO] Preparing go2rtc config...
2023-03-10 09:29:50.689144377  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-03-10 09:29:50.724006027  [INFO] Starting go2rtc...
2023-03-10 09:29:50.819877975  09:29:50.819 INF go2rtc version 1.2.0 linux/amd64
2023-03-10 09:29:50.820124778  09:29:50.820 INF [api] listen addr=:1984
2023-03-10 09:29:50.820614333  09:29:50.820 INF [srtp] listen addr=:8443
2023-03-10 09:29:50.820791077  09:29:50.820 INF [webrtc] listen addr=:8555
2023-03-10 09:30:00.374322169  [INFO] Starting go2rtc healthcheck service...
2023-03-10 10:07:46.429609043  10:07:46.429 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:40110->192.168.103.4:554: i/o timeout" url=rtsp://admin:*********@192.168.103.4:554
2023-03-10 10:08:01.990564289  10:08:01.990 WRN [streams] json locked
2023-03-10 10:08:31.999442271  10:08:31.999 WRN [streams] json locked
2023-03-10 10:09:02.018951092  10:09:02.018 WRN [streams] json locked
2023-03-10 10:09:32.029408920  10:09:32.029 WRN [streams] json locked
2023-03-10 10:09:35.816804016  panic: runtime error: invalid memory address or nil pointer dereference
2023-03-10 10:09:35.817566881  [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7a1ebe]
2023-03-10 10:09:35.817574115  
2023-03-10 10:09:35.817578999  goroutine 181 [running]:
2023-03-10 10:09:35.817584077  github.com/AlexxIT/go2rtc/pkg/streamer.(*Track).GetSink(0x0, 0xc000187440)
2023-03-10 10:09:35.817595798  	github.com/AlexxIT/go2rtc/pkg/streamer/track.go:77 +0x1e
2023-03-10 10:09:35.817600921  github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).reconnect(0xc00018a870, 0x3)
2023-03-10 10:09:35.817636382  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:173 +0x5ee
2023-03-10 10:09:35.817644606  github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).worker(0xc00018a870, {0xcc2920?, 0xc00013a4b0?}, 0x3)
2023-03-10 10:09:35.817649708  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:136 +0x15b
2023-03-10 10:09:35.817654350  created by github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).start
2023-03-10 10:09:35.817692719  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:120 +0x1be
2023-03-10 10:09:35.857262961  [INFO] The go2rtc service exited with code 2 (by signal 0)
2023-03-10 10:09:36.861726481  [INFO] Starting go2rtc...
2023-03-10 10:09:36.938117172  10:09:36.938 INF go2rtc version 1.2.0 linux/amd64
2023-03-10 10:09:36.938381783  10:09:36.938 INF [api] listen addr=:1984
2023-03-10 10:09:36.938940634  10:09:36.938 INF [srtp] listen addr=:8443
2023-03-10 10:09:36.939100648  10:09:36.939 INF [webrtc] listen addr=:8555
2023-03-10 12:13:56.376958215  12:13:56.376 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:55054->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:14:25.948626968  12:14:25.948 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:32870->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:14:30.793573208  panic: runtime error: invalid memory address or nil pointer dereference
2023-03-10 12:14:30.793976703  [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7a1ebe]
2023-03-10 12:14:30.793983575  
2023-03-10 12:14:30.793988208  goroutine 133 [running]:
2023-03-10 12:14:30.793993482  github.com/AlexxIT/go2rtc/pkg/streamer.(*Track).GetSink(0x0, 0xc0001a6f60)
2023-03-10 12:14:30.793998515  	github.com/AlexxIT/go2rtc/pkg/streamer/track.go:77 +0x1e
2023-03-10 12:14:30.794004363  github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).reconnect(0xc0001aa7e0, 0x13)
2023-03-10 12:14:30.794009757  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:173 +0x5ee
2023-03-10 12:14:30.794016015  github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).worker(0xc0001aa7e0, {0xcc2920?, 0xc0000b4690?}, 0x13)
2023-03-10 12:14:30.794020881  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:136 +0x15b
2023-03-10 12:14:30.794026120  created by github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).start
2023-03-10 12:14:30.794031533  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:120 +0x1be
2023-03-10 12:14:30.813763310  [INFO] The go2rtc service exited with code 2 (by signal 0)
2023-03-10 12:14:31.825304924  [INFO] Starting go2rtc...
2023-03-10 12:14:31.894371380  12:14:31.894 INF go2rtc version 1.2.0 linux/amd64
2023-03-10 12:14:31.894664289  12:14:31.894 INF [api] listen addr=:1984
2023-03-10 12:14:31.895091916  12:14:31.895 INF [srtp] listen addr=:8443
2023-03-10 12:14:31.895265455  12:14:31.895 INF [webrtc] listen addr=:8555
2023-03-10 12:14:39.745196071  12:14:39.744 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:40064->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:15:00.118191449  12:15:00.117 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:40068->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:16:13.555440195  12:16:13.555 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:50668->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:16:39.752873363  12:16:39.752 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:36502->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:17:25.008295733  12:17:25.007 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:37070->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:17:42.776099581  12:17:42.775 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:38838->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:18:08.514792409  12:18:08.514 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:35590->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:19:14.361705931  12:19:14.361 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:52676->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:19:33.549585463  12:19:33.549 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:40918->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:55:30.243037134  12:55:30.242 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:37280->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:55:50.609223859  12:55:50.608 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:34248->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:57:30.032529903  12:57:30.032 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:58848->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:57:48.492819413  12:57:48.492 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:47446->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:58:26.250592075  12:58:26.250 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:40940->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:59:01.435868413  12:59:01.435 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:55868->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 12:59:22.679951255  12:59:22.679 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:35442->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 13:00:13.688759021  13:00:13.688 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:35086->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 13:00:30.614371231  13:00:30.614 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="dial tcp 192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 13:01:17.018174204  13:01:17.018 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:60874->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 13:03:48.360713888  13:03:48.360 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:57266->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 13:04:15.536288023  13:04:15.534 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:47722->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 13:11:27.566123471  13:11:27.565 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:55768->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 13:11:52.105836261  13:11:52.105 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:47006->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 13:14:06.731722109  13:14:06.731 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:35672->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 13:14:38.065520553  13:14:38.065 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:58560->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 13:14:50.126761703  13:14:50.126 ERR github.com/AlexxIT/go2rtc/cmd/streams/producer.go:53 > error="dial tcp 192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 13:15:08.699244314  13:15:08.699 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:54212->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 13:15:58.533151467  13:15:58.531 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:54004->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 13:16:57.363660944  13:16:57.363 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="RTSP wrong input" url=rtsp://tapo_admin:*********@192.168.103.45/stream1
2023-03-10 13:37:24.593082148  13:37:24.592 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="RTSP wrong input" url=rtsp://tapo_admin:*********@192.168.103.45/stream1
2023-03-10 13:44:55.580394781  13:44:55.580 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="read tcp 192.168.102.30:49126->192.168.103.5:554: i/o timeout" url=rtsp://admin:*********@192.168.103.5:554
2023-03-10 14:09:36.686117967  14:09:36.685 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="RTSP wrong input" url=rtsp://tapo_admin:*********@192.168.103.45/stream1
2023-03-10 14:11:41.204159503  14:11:41.203 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:133 > error="RTSP wrong input" url=rtsp://tapo_admin:*********@192.168.103.45/stream1
```

**Comment by bagobones** [comment]
This is happening 1 - 2 times a day with the majority of my cameras constant streaming via frigate.. From the look of it is may be related to a camera becoming disconnected and reconnected.

```
2023-03-12 17:33:04.827199234  panic: runtime error: invalid memory address or nil pointer dereference
2023-03-12 17:33:04.827206404  [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7a1ebe]
2023-03-12 17:33:04.827209511  
2023-03-12 17:33:04.827212702  goroutine 382 [running]:
2023-03-12 17:33:04.827245148  github.com/AlexxIT/go2rtc/pkg/streamer.(*Track).GetSink(0x0, 0xc000116bd0)
2023-03-12 17:33:04.827248363  	github.com/AlexxIT/go2rtc/pkg/streamer/track.go:77 +0x1e
2023-03-12 17:33:04.827272631  github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).reconnect(0xc0000f2a20, 0x11)
2023-03-12 17:33:04.827295131  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:173 +0x5ee
2023-03-12 17:33:04.827338702  github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).worker(0xc0000f2a20, {0xcc2920?, 0xc0002944b0?}, 0x11)
2023-03-12 17:33:04.827362926  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:136 +0x15b
2023-03-12 17:33:04.827385052  created by github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).start
2023-03-12 17:33:04.827418241  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:120 +0x1be
```

**Comment by AlexxIT** [comment]
Same as #135
Will be fixed in next release

**Comment by AlexxIT** [comment]
Fixed in latest releases
