### ISSUE TITLE
Wrong SDP from Ezviz C6N

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/go2rtc#264]
Camera support only H264 codec

```
21:34:57.273 INF [streams] create new stream url=rtsp://admin:xxx@192.168.1.58:554/h264_stream
21:34:57.277 TRC [rtsp] client request:
DESCRIBE rtsp://192.168.1.58:554/h264_stream RTSP/1.0
Accept: application/sdp
Require: www.onvif.org/ver20/backchannel
User-Agent: go2rtc/1.1.2
CSeq: 1

21:34:57.293 TRC [rtsp] client response:
RTSP/1.0 401 Unauthorized
Www-Authenticate: xxx
Date: Thu, Feb 16 2023 21:34:57 GMT
Cseq: 1

21:34:57.293 TRC [rtsp] client request:
DESCRIBE rtsp://192.168.1.58:554/h264_stream RTSP/1.0
User-Agent: go2rtc/1.1.2
CSeq: 2
Authorization: xxx
Accept: application/sdp
Require: www.onvif.org/ver20/backchannel

21:34:57.305 TRC [rtsp] client response:
RTSP/1.0 200 OK
Content-Base: rtsp://192.168.1.58:554/h264_stream/
Cseq: 2
Content-Type: application/sdp
Content-Length: 480

v=0
o=- 1676583297494652 1676583297494652 IN IP4 192.168.1.58
s=Media Presentation
e=NONE
b=AS:5050
t=0 0
a=control:rtsp://192.168.1.58:554/h264_stream/
m=video 0 RTP/AVP 96
b=AS:5000
a=control:rtsp://192.168.1.58:554/h264_stream/trackID=1
a=rtpmap:96 H265/90000
a=fmtp:96 profile-level-id=420029; packetization-mode=1; sprop-parameter-sets=
a=Media_header:MEDIAINFO=494D4B48010100000400050000000000000000000000000000000000000000000000000000000000;
a=appversion:1.0
21:34:57.306 TRC [rtsp] client request:
SETUP rtsp://192.168.1.58:554/h264_stream/trackID=1 RTSP/1.0
Transport: RTP/AVP/TCP;unicast;interleaved=0-1
CSeq: 3
Authorization: xxx

21:34:57.316 TRC [rtsp] client response:
RTSP/1.0 200 OK
Cseq: 3
Session: 398474722;timeout=20
Transport: RTP/AVP/TCP;unicast;interleaved=0-1;ssrc=4e18b10f;mode="play"
Date: Thu, Feb 16 2023 21:34:57 GMT

panic: runtime error: index out of range [3] with length 0
goroutine 34 [running]:
github.com/deepch/vdk/codec/h265parser.NewCodecDataFromVPSAndSPSAndPPS({_, _, _}, {_, _, _}, {_, _, _})
  github.com/deepch/vdk@v0.0.19/codec/h265parser/parser.go:504 +0x404
github.com/AlexxIT/go2rtc/pkg/mp4.(*Muxer).GetInit(0x40003ba040, {0x400000e040, 0x1, 0x718d60?})
  github.com/AlexxIT/go2rtc/pkg/mp4/muxer.go:89 +0x4d0
github.com/AlexxIT/go2rtc/pkg/mp4.(*Consumer).Init(...)
  github.com/AlexxIT/go2rtc/pkg/mp4/consumer.go:184
github.com/AlexxIT/go2rtc/cmd/mp4.handlerWSMSE(0x4000226120, 0x400020a020)
  github.com/AlexxIT/go2rtc/cmd/mp4/ws.go:52 +0x4c8
github.com/AlexxIT/go2rtc/cmd/api.apiWS.func2()
  github.com/AlexxIT/go2rtc/cmd/api/ws.go:93 +0x3c
created by github.com/AlexxIT/go2rtc/cmd/api.apiWS
  github.com/AlexxIT/go2rtc/cmd/api/ws.go:92 +0x314
```

**Comment by AlexxIT** [comment]
Fixed https://github.com/AlexxIT/go2rtc/releases/tag/v1.2.0
