### ISSUE TITLE
Fix panic on processing RTCP from HomeKit cameras

### ISSUE THREAD

**Issue by sdavides** [AlexxIT/go2rtc#287]
sometimes I find the stopped component with the error:
```
12:21:46.936 INF go2rtc version 1.2.0 linux/amd64
12:21:46.938 INF [api] listen addr=:1984
12:21:46.945 INF [rtsp] listen addr=:8554
12:21:46.955 INF [hass] load stream url=hass:Camera-Hub-G3-120C
12:21:46.958 INF [srtp] listen addr=:8443
12:21:46.965 INF [webrtc] listen addr=:8555
12:21:52.689 INF [streams] create new stream url=hass:Camera-Hub-G3-120C
2023/03/15 12:21:53 [INFO] mdns: Closing client {true false 0xc0000129c8 <nil> 0xc0000129d0 <nil> 1 0xc000047a40}
2023/03/15 12:22:46 [INFO] mdns: Closing client {true false 0xc000012a20 <nil> 0xc000012a28 <nil> 1 0xc000046de0}
2023/03/15 12:23:24 [INFO] mdns: Closing client {true false 0xc000012db8 <nil> 0xc000012dc0 <nil> 1 0xc00041b860}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa3e053]
goroutine 8 [running]:
github.com/AlexxIT/go2rtc/pkg/srtp.(*Session).KeepAlive(0xc000234f00)
	github.com/AlexxIT/go2rtc/pkg/srtp/session.go:138 +0x133
github.com/AlexxIT/go2rtc/pkg/srtp.(*Session).HandleRTCP(0xc000234f00, {0xc00017a000?, 0xab179cbc?, 0x800?})
	github.com/AlexxIT/go2rtc/pkg/srtp/session.go:104 +0x89
github.com/AlexxIT/go2rtc/pkg/srtp.(*Server).Serve(0xc000010d68, {0xcc5120?, 0xc000012808})
	github.com/AlexxIT/go2rtc/pkg/srtp/server.go:71 +0x205
github.com/AlexxIT/go2rtc/cmd/srtp.Init.func1()
	github.com/AlexxIT/go2rtc/cmd/srtp/srtp.go:39 +0x85
created by github.com/AlexxIT/go2rtc/cmd/srtp.Init
	github.com/AlexxIT/go2rtc/cmd/srtp/srtp.go:37 +0x28f
```

**Comment by mortenmoulder** [comment]
Yeah I get the same. It happens when one of my cameras (attached to my robot lawnmower) disconnects from WiFi while driving around.

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.0
