### ISSUE TITLE
Crashing with unstable stream

### ISSUE THREAD

**Issue by roger-** [AlexxIT/go2rtc#296]
I'm running 1.20 (via Frigate) and getting the following crash once in a while:

```
2023-03-19 17:34:51.044502902  17:34:51.044 WRN [rtsp] error="source 0 error: wrong response on DESCRIBE" stream=back_porch_high
2023-03-19 17:34:51.044607938  17:34:51.044 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:221 > error="write tcp 127.0.0.1:8554->127.0.0.1:57904: write: broken pipe"
2023-03-19 17:34:59.787721488  panic: runtime error: invalid memory address or nil pointer dereference
2023-03-19 17:34:59.787724905  [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7cf7b7]
2023-03-19 17:34:59.787725964  
2023-03-19 17:34:59.787727191  goroutine 306 [running]:
2023-03-19 17:34:59.787728482  github.com/AlexxIT/go2rtc/pkg/tcp.(*Request).Write(0xb50b40?, {0x0, 0x0})
2023-03-19 17:34:59.787743500  	github.com/AlexxIT/go2rtc/pkg/tcp/textproto.go:108 +0x37
2023-03-19 17:34:59.787744865  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Request(0xc0000201e0, 0xc0002ac460)
2023-03-19 17:34:59.787746054  	github.com/AlexxIT/go2rtc/pkg/rtsp/client.go:188 +0x405
2023-03-19 17:34:59.787747210  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Do(0xc0000201e0, 0xc0002ac460)
2023-03-19 17:34:59.787754171  	github.com/AlexxIT/go2rtc/pkg/rtsp/client.go:193 +0x27
2023-03-19 17:34:59.787760788  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).SetupMedia(0xc0000201e0, 0xc0003461e0, 0xc00024aab0, 0x78?)
2023-03-19 17:34:59.787767123  	github.com/AlexxIT/go2rtc/pkg/rtsp/client.go:396 +0x5ce
2023-03-19 17:34:59.787773920  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).GetTrack(0x0?, 0x0?, 0xc00020c0fa?)
2023-03-19 17:34:59.787780395  	github.com/AlexxIT/go2rtc/pkg/rtsp/producer.go:46 +0x159
2023-03-19 17:34:59.787789297  github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).GetTrack(0xc0001aa3f0, 0xbcde2c?, 0x0?)
2023-03-19 17:34:59.787795795  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:82 +0x145
2023-03-19 17:34:59.787831063  github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc0001e8600, {0xcc01b8?, 0xc00011e0f0})
2023-03-19 17:34:59.787838324  	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:83 +0x86d
2023-03-19 17:34:59.787850432  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler.func1({0xab96e0?, 0xcba390?})
2023-03-19 17:34:59.787857794  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:185 +0x5e5
2023-03-19 17:34:59.787864499  github.com/AlexxIT/go2rtc/pkg/streamer.(*Element).Fire(...)
2023-03-19 17:34:59.787865674  	github.com/AlexxIT/go2rtc/pkg/streamer/streamer.go:27
2023-03-19 17:34:59.787872878  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Accept(0xc00011e0f0)
2023-03-19 17:34:59.787879887  	github.com/AlexxIT/go2rtc/pkg/rtsp/server.go:96 +0xc97
2023-03-19 17:34:59.787881054  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler(0xc00011e0f0)
2023-03-19 17:34:59.787888245  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:220 +0x1a7
2023-03-19 17:34:59.787895083  created by github.com/AlexxIT/go2rtc/cmd/rtsp.Init.func1
2023-03-19 17:34:59.787896219  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:72 +0x48
```

Not entirely sure which stream is causing the crash.

**Comment by AlexxIT** [comment]
Please check if probles still exist in 1.3.0. The streaming core was rewriten. Can't fix it in old version
