### ISSUE TITLE
JSON locked after camera stream crashes

### ISSUE THREAD

**Issue by NickM-27** [AlexxIT/go2rtc#301]
Running on 1.3.0 I am seeing that when using RTSP (no viewing of webrtc or mse) after some period of time a camera stream will go down and the go2rtc log gets filled with JSON locked

```
2023-03-23 11:59:15.427205487  [INFO] Preparing go2rtc config...
2023-03-23 11:59:15.695051741  [INFO] Not injecting WebRTC candidates into go2rtc config as it has been set manually
2023-03-23 11:59:15.713270715  [INFO] Starting go2rtc...
2023-03-23 11:59:15.761878775  11:59:15.761 INF go2rtc version 1.3.0 linux/amd64
2023-03-23 11:59:15.762255041  11:59:15.762 INF [api] listen addr=:1984
2023-03-23 11:59:15.762512115  11:59:15.762 INF [rtsp] listen addr=:8554
2023-03-23 11:59:15.762935021  11:59:15.762 INF [webrtc] listen addr=:8555/tcp
2023-03-23 11:59:25.274535121  11:59:25.274 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:214 > error=EOF
2023-03-23 11:59:25.427016142  [INFO] Starting go2rtc healthcheck service...
2023-03-23 11:59:25.459102154  11:59:25.459 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:214 > error=EOF
2023-03-23 13:04:51.719789310  13:04:51.719 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error=EOF url=ffmpeg:http://192.168.50.150/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=password#input=http-reolink#video=copy#audio=copy#audio=opus
2023-03-23 13:05:26.405103391  13:05:26.405 WRN [streams] json locked
2023-03-23 13:05:56.414045700  13:05:56.414 WRN [streams] json locked
2023-03-23 13:06:26.422367865  13:06:26.422 WRN [streams] json locked
2023-03-23 13:06:56.429886675  13:06:56.429 WRN [streams] json locked
2023-03-23 13:07:26.437290614  13:07:26.437 WRN [streams] json locked
2023-03-23 13:07:56.445570355  13:07:56.445 WRN [streams] json locked
2023-03-23 13:08:26.454316548  13:08:26.454 WRN [streams] json locked
2023-03-23 13:08:56.460862862  13:08:56.460 WRN [streams] json locked
2023-03-23 13:09:26.468455666  13:09:26.468 WRN [streams] json locked
2023-03-23 13:09:56.478543708  13:09:56.478 WRN [streams] json locked
2023-03-23 13:10:26.486073344  13:10:26.486 WRN [streams] json locked
2023-03-23 13:10:56.493898004  13:10:56.493 WRN [streams] json locked
2023-03-23 13:11:26.502441598  13:11:26.502 WRN [streams] json locked
2023-03-23 13:11:56.509076058  13:11:56.509 WRN [streams] json locked
2023-03-23 13:12:26.517015798  13:12:26.516 WRN [streams] json locked
2023-03-23 13:12:56.525867019  13:12:56.525 WRN [streams] json locked
2023-03-23 13:13:26.533062318  13:13:26.533 WRN [streams] json locked
2023-03-23 13:13:56.541241406  13:13:56.541 WRN [streams] json locked
2023-03-23 13:14:26.549605500  13:14:26.549 WRN [streams] json locked
2023-03-23 13:14:56.583111844  13:14:56.583 WRN [streams] json locked
2023-03-23 13:15:26.590997313  13:15:26.590 WRN [streams] json locked
2023-03-23 13:15:56.598188465  13:15:56.598 WRN [streams] json locked
2023-03-23 13:16:26.607336775  13:16:26.607 WRN [streams] json locked
2023-03-23 13:16:56.615481274  13:16:56.615 WRN [streams] json locked
2023-03-23 13:17:26.622469969  13:17:26.622 WRN [streams] json locked
2023-03-23 13:17:56.630202683  13:17:56.630 WRN [streams] json locked
2023-03-23 13:18:26.637581913  13:18:26.637 WRN [streams] json locked
2023-03-23 13:18:56.644116931  13:18:56.644 WRN [streams] json locked
2023-03-23 13:19:26.652981558  13:19:26.652 WRN [streams] json locked
2023-03-23 13:19:56.661914094  13:19:56.661 WRN [streams] json locked
2023-03-23 13:20:26.672060327  13:20:26.672 WRN [streams] json locked
2023-03-23 13:20:56.680972464  13:20:56.680 WRN [streams] json locked
2023-03-23 13:21:26.687680712  13:21:26.687 WRN [streams] json locked
2023-03-23 13:21:56.694741405  13:21:56.694 WRN [streams] json locked
2023-03-23 13:22:26.704431863  13:22:26.704 WRN [streams] json locked
2023-03-23 13:22:56.713645651  13:22:56.713 WRN [streams] json locked
2023-03-23 13:23:26.722898937  13:23:26.722 WRN [streams] json locked
2023-03-23 13:23:56.728860781  13:23:56.728 WRN [streams] json locked
2023-03-23 13:24:26.735821502  13:24:26.735 WRN [streams] json locked
2023-03-23 13:24:56.743684650  13:24:56.743 WRN [streams] json locked
2023-03-23 13:25:26.752879502  13:25:26.752 WRN [streams] json locked
2023-03-23 13:25:56.761800933  13:25:56.761 WRN [streams] json locked
2023-03-23 13:26:26.770327680  13:26:26.770 WRN [streams] json locked
2023-03-23 13:26:56.778322764  13:26:56.778 WRN [streams] json locked
2023-03-23 13:27:26.786183515  13:27:26.786 WRN [streams] json locked
2023-03-23 13:27:56.792839853  13:27:56.792 WRN [streams] json locked
2023-03-23 13:28:26.801116192  13:28:26.801 WRN [streams] json locked
2023-03-23 13:28:56.809861403  13:28:56.809 WRN [streams] json locked
2023-03-23 13:29:26.817089263  13:29:26.817 WRN [streams] json locked
2023-03-23 13:29:56.825723051  13:29:56.825 WRN [streams] json locked
2023-03-23 13:30:26.831786298  13:30:26.831 WRN [streams] json locked
2023-03-23 13:30:56.840446991  13:30:56.840 WRN [streams] json locked
2023-03-23 13:31:26.849282996  13:31:26.849 WRN [streams] json locked
2023-03-23 13:31:56.857862495  13:31:56.857 WRN [streams] json locked
2023-03-23 13:32:26.866611814  13:32:26.866 WRN [streams] json locked
2023-03-23 13:32:56.873488787  13:32:56.873 WRN [streams] json locked
2023-03-23 13:33:26.880684756  13:33:26.880 WRN [streams] json locked
2023-03-23 13:33:56.888616495  13:33:56.888 WRN [streams] json locked
2023-03-23 13:34:26.895563716  13:34:26.895 WRN [streams] json locked
2023-03-23 13:34:56.901892372  13:34:56.901 WRN [streams] json locked
2023-03-23 13:35:26.911214709  13:35:26.911 WRN [streams] json locked
2023-03-23 13:35:56.920596083  13:35:56.920 WRN [streams] json locked
2023-03-23 13:36:26.929019626  13:36:26.928 WRN [streams] json locked
2023-03-23 13:36:56.936674842  13:36:56.936 WRN [streams] json locked
2023-03-23 13:37:26.944839880  13:37:26.944 WRN [streams] json locked
2023-03-23 13:37:56.952610477  13:37:56.952 WRN [streams] json locked
2023-03-23 13:38:26.960082800  13:38:26.960 WRN [streams] json locked
2023-03-23 13:38:56.967564351  13:38:56.967 WRN [streams] json locked
2023-03-23 13:39:26.977377242  13:39:26.977 WRN [streams] json locked
2023-03-23 13:39:56.984816864  13:39:56.984 WRN [streams] json locked
2023-03-23 13:40:26.993708389  13:40:26.993 WRN [streams] json locked
2023-03-23 13:40:57.003681691  13:40:57.003 WRN [streams] json locked
2023-03-23 13:41:27.011113931  13:41:27.011 WRN [streams] json locked
2023-03-23 13:41:57.018402430  13:41:57.018 WRN [streams] json locked
2023-03-23 13:42:27.026176164  13:42:27.026 WRN [streams] json locked
2023-03-23 13:42:57.032562907  13:42:57.032 WRN [streams] json locked
2023-03-23 13:43:27.039189003  13:43:27.039 WRN [streams] json locked
2023-03-23 13:43:57.047709591  13:43:57.047 WRN [streams] json locked
2023-03-23 13:44:27.055642684  13:44:27.055 WRN [streams] json locked
2023-03-23 13:44:57.065497203  13:44:57.065 WRN [streams] json locked
2023-03-23 13:45:27.073902647  13:45:27.073 WRN [streams] json locked
2023-03-23 13:45:57.081506568  13:45:57.081 WRN [streams] json locked
2023-03-23 13:46:27.087737537  13:46:27.087 WRN [streams] json locked
2023-03-23 13:46:57.095012862  13:46:57.094 WRN [streams] json locked
2023-03-23 13:47:27.103561948  13:47:27.103 WRN [streams] json locked
2023-03-23 13:47:57.111419453  13:47:57.111 WRN [streams] json locked
2023-03-23 13:48:27.117589584  13:48:27.117 WRN [streams] json locked
2023-03-23 13:48:57.126436830  13:48:57.126 WRN [streams] json locked
2023-03-23 13:49:27.135630992  13:49:27.135 WRN [streams] json locked
2023-03-23 13:49:57.143955831  13:49:57.143 WRN [streams] json locked
2023-03-23 13:50:27.151232344  13:50:27.151 WRN [streams] json locked
2023-03-23 13:50:57.159996130  13:50:57.159 WRN [streams] json locked
2023-03-23 13:51:27.177794822  13:51:27.177 WRN [streams] json locked
2023-03-23 13:51:57.185614192  13:51:57.185 WRN [streams] json locked
2023-03-23 13:52:27.193649923  13:52:27.193 WRN [streams] json locked
2023-03-23 13:52:57.200993781  13:52:57.200 WRN [streams] json locked
2023-03-23 13:53:27.208030841  13:53:27.207 WRN [streams] json locked
```

**Comment by AlexxIT** [comment]
It's strange. This is the initial stream setting. At this point it has not yet started:
`github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:214`

**Comment by xakepShilo** [comment]
Да, есть такое дело!
Камера перестает передавать поток - помогает только перезагрузка go2rtc.

Логи не выкладываю, ибо в моих тоже самое.

**Comment by NickM-27** [comment]
@AlexxIT is there any kind of logging I can enable to provide more info?

**Comment by AlexxIT** [comment]
Several users have reported this problem. I think I can find it myself

**Comment by NickM-27** [comment]
@AlexxIT I tried the latest commit and saw this:

```
2023-03-25 06:45:19.700608036  [INFO] Starting go2rtc...
2023-03-25 06:45:19.709844741  06:45:19.709 INF go2rtc version 1.3.0 linux/amd64
2023-03-25 06:45:19.710051654  06:45:19.710 INF [api] listen addr=:1984
2023-03-25 06:45:19.710450900  06:45:19.710 INF [rtsp] listen addr=:8554
2023-03-25 06:45:19.711157690  06:45:19.711 INF [webrtc] listen addr=:8555/tcp
2023-03-25 06:45:41.058130602  06:45:41.057 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 172.17.0.8:40160->192.168.50.151:554: i/o timeout" url=rtsp://user:pass@192.168.50.151/Preview_01_main#backchannel=0
2023-03-25 06:45:41.072834127  06:45:41.072 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 172.17.0.8:58294->192.168.50.155:554: i/o timeout" url=rtsp://user:pass@192.168.50.155/Preview_01_main
2023-03-25 06:45:49.179236588  06:45:49.179 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 172.17.0.8:33568->192.168.50.151:554: i/o timeout" url=rtsp://user:pass@192.168.50.151/Preview_01_main#backchannel=0
2023-03-25 06:45:49.199377772  06:45:49.199 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 172.17.0.8:41656->192.168.50.155:554: i/o timeout" url=rtsp://user:pass@192.168.50.155/Preview_01_main
2023-03-25 06:45:49.312343200  06:45:49.312 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error=EOF url=ffmpeg:http://192.168.50.154/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass#input=http-reolink#video=copy#audio=copy#audio=opus
2023-03-25 06:45:51.048654644  06:45:51.048 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 127.0.0.1:8554->127.0.0.1:36148: i/o timeout" url=ffmpeg:http://192.168.50.150/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass#input=http-reolink#video=copy#audio=copy#audio=opus
2023-03-25 06:45:58.400852394  06:45:58.400 WRN [rtsp] error="sources unavailable: 2" stream=garage_cam_sub
2023-03-25 06:45:58.400960375  06:45:58.400 WRN [rtsp] error="sources unavailable: 2" stream=garage_cam_sub
2023-03-25 06:45:58.695050657  06:45:58.694 WRN [rtsp] error="sources unavailable: 2" stream=office_cam_sub
2023-03-25 06:45:58.695082358  06:45:58.694 WRN [rtsp] error="sources unavailable: 2" stream=office_cam_sub
2023-03-25 06:46:03.558849754  06:46:03.558 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 172.17.0.8:45398->192.168.50.151:554: i/o timeout" url=rtsp://user:pass@192.168.50.151/Preview_01_main#backchannel=0
2023-03-25 06:46:12.874945263  06:46:12.874 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:214 > error=EOF
2023-03-25 06:46:12.874976643  06:46:12.874 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:214 > error=EOF
2023-03-25 06:46:13.687547060  06:46:13.687 WRN [rtsp] error="sources unavailable: 3" stream=backyard_cam_sub
2023-03-25 06:46:15.320542693  06:46:15.320 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:214 > error=EOF
2023-03-25 06:46:15.368155908  06:46:15.368 WRN [rtsp] error="sources unavailable: 2" stream=garage_cam_sub
2023-03-25 06:46:15.506001848  06:46:15.505 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:214 > error=EOF
2023-03-25 06:46:15.675462571  06:46:15.675 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:214 > error=EOF
2023-03-25 06:46:15.722570198  06:46:15.722 WRN [rtsp] error="sources unavailable: 2" stream=office_cam_sub
2023-03-25 06:46:18.330088298  06:46:18.330 WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:214 > error=EOF
2023-03-25 06:46:19.430816459  06:46:19.430 WRN [rtsp] error="sources unavailable: 3" stream=front_doorbell_cam_sub
2023-03-25 06:46:19.430858479  06:46:19.430 WRN [rtsp] error="sources unavailable: 3" stream=front_doorbell_cam_sub
2023-03-25 06:46:37.959516229  06:46:37.959 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 172.17.0.8:37654->192.168.50.151:554: i/o timeout" url=rtsp://user:pass@192.168.50.151/Preview_01_main#backchannel=0
2023-03-25 06:46:37.973611745  06:46:37.973 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 172.17.0.8:33120->192.168.50.155:554: i/o timeout" url=rtsp://user:pass@192.168.50.155/Preview_01_main
2023-03-25 06:46:43.120906668  06:46:43.120 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error=EOF url="ffmpeg:front_doorbell_cam#video=h264#width=1280#height=960#raw=-fpsmax 10#hardware=cuda"
2023-03-25 06:46:43.188758908  06:46:43.188 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error=EOF url="ffmpeg:backyard_cam#video=h264#width=1280#height=960#raw=-fpsmax 10#hardware=cuda"
2023-03-25 06:46:47.931002581  06:46:47.930 WRN github.com/AlexxIT/go2rtc/cmd/streams/producer.go:157 > error="read tcp 127.0.0.1:8554->127.0.0.1:57554: i/o timeout" url=ffmpeg:http://192.168.50.150/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=user&password=pass#input=http-reolink#video=copy#audio=copy#audio=opus
2023-03-25 06:46:51.674995951  panic: runtime error: invalid memory address or nil pointer dereference
2023-03-25 06:46:51.675001461  [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7aef9f]
2023-03-25 06:46:51.675003261  
2023-03-25 06:46:51.675004681  goroutine 334 [running]:
2023-03-25 06:46:51.675027432  github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).GetMedias(0xc0002d28c0?)
2023-03-25 06:46:51.675029072  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:61 +0x9f
2023-03-25 06:46:51.675030642  github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc00021b140, {0xd36f18, 0xc000263400})
2023-03-25 06:46:51.675031972  	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:69 +0x4d2
2023-03-25 06:46:51.675041382  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler.func1({0xb12440?, 0xd30c60?})
2023-03-25 06:46:51.675042802  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:181 +0x599
2023-03-25 06:46:51.675044212  github.com/AlexxIT/go2rtc/pkg/core.(*Listener).Fire(...)
2023-03-25 06:46:51.675051962  	github.com/AlexxIT/go2rtc/pkg/core/listener.go:16
2023-03-25 06:46:51.675053372  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Accept(0xc000263400)
2023-03-25 06:46:51.675054662  	github.com/AlexxIT/go2rtc/pkg/rtsp/server.go:92 +0xb88
2023-03-25 06:46:51.675061432  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler(0xc000263400)
2023-03-25 06:46:51.675062862  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:213 +0x1a7
2023-03-25 06:46:51.675070412  created by github.com/AlexxIT/go2rtc/cmd/rtsp.Init.func1
2023-03-25 06:46:51.675071732  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:72 +0x48
```

**Comment by NickM-27** [comment]
here's a different one with a somewhat different looking stacktrace

```
2023-03-25 06:45:18.681574440  panic: runtime error: invalid memory address or nil pointer dereference
2023-03-25 06:45:18.681578590  [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7aef9f]
2023-03-25 06:45:18.681579870  
2023-03-25 06:45:18.681580920  goroutine 451 [running]:
2023-03-25 06:45:18.681603450  github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).GetMedias(0xc0002a3b80?)
2023-03-25 06:45:18.681604580  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:61 +0x9f
2023-03-25 06:45:18.681605640  github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc0001d0b00, {0xd36f18, 0xc000388900})
2023-03-25 06:45:18.681606590  	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:69 +0x4d2
2023-03-25 06:45:18.681607470  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler.func1({0xb12440?, 0xd30c60?})
2023-03-25 06:45:18.681625611  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:181 +0x599
2023-03-25 06:45:18.681627631  github.com/AlexxIT/go2rtc/pkg/core.(*Listener).Fire(...)
2023-03-25 06:45:18.681628711  	github.com/AlexxIT/go2rtc/pkg/core/listener.go:16
2023-03-25 06:45:18.681636911  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Accept(0xc000388900)
2023-03-25 06:45:18.681637981  	github.com/AlexxIT/go2rtc/pkg/rtsp/server.go:92 +0xb88
2023-03-25 06:45:18.681638961  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler(0xc000388900)
2023-03-25 06:45:18.681639891  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:213 +0x1a7
2023-03-25 06:45:18.681640801  created by github.com/AlexxIT/go2rtc/cmd/rtsp.Init.func1
2023-03-25 06:45:18.681641671  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:72 +0x48
2023-03-25 06:45:18.689072339  panic: runtime error: invalid memory address or nil pointer dereference
2023-03-25 06:45:18.689085600  [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7aef9f]
2023-03-25 06:45:18.689086950  
2023-03-25 06:45:18.689088260  goroutine 400 [running]:
2023-03-25 06:45:18.689096360  github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).GetMedias(0xc0002a3b80?)
2023-03-25 06:45:18.689098010  	github.com/AlexxIT/go2rtc/cmd/streams/producer.go:61 +0x9f
2023-03-25 06:45:18.689106130  github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc0001d0b00, {0xd36f18, 0xc00013aa00})
2023-03-25 06:45:18.689107760  	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:69 +0x4d2
2023-03-25 06:45:18.689115450  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler.func1({0xb12440?, 0xd30c60?})
2023-03-25 06:45:18.689123220  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:181 +0x599
2023-03-25 06:45:18.689124770  github.com/AlexxIT/go2rtc/pkg/core.(*Listener).Fire(...)
2023-03-25 06:45:18.689135140  	github.com/AlexxIT/go2rtc/pkg/core/listener.go:16
2023-03-25 06:45:18.689136710  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Accept(0xc00013aa00)
2023-03-25 06:45:18.689138160  	github.com/AlexxIT/go2rtc/pkg/rtsp/server.go:92 +0xb88
2023-03-25 06:45:18.689146150  github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler(0xc00013aa00)
2023-03-25 06:45:18.689147641  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:213 +0x1a7
2023-03-25 06:45:18.689149071  created by github.com/AlexxIT/go2rtc/cmd/rtsp.Init.func1
2023-03-25 06:45:18.689156811  	github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:72 +0x48
```

**Comment by AlexxIT** [comment]
Should be fixed https://github.com/AlexxIT/go2rtc/releases/tag/v1.3.1
