### ISSUE TITLE
Panic: streams.(*Stream).RemoveConsumer

### ISSUE THREAD

**Issue by maxi1134** [AlexxIT/go2rtc#31]
Hi, I am using Beta 11, and the software seems to crash after 20-22 hours of runnings and then needs to be restarted.

This is the error that is spammed when that happens;

`2022/09/03 04:54:54 http: panic serving 192.168.0.15:47054: runtime error: invalid memory address or nil pointer dereference`
Which is odd since the machine still has free ram

**Comment by AlexxIT** [comment]
You need to provide full error with lines numbers.

**Comment by maxi1134** [comment]
Sorry for that;

https://pastebin.com/5kpmecyB

**Comment by AlexxIT** [comment]
I think I already fix this bug. Will be in next release.

**Comment by calisro** [comment]
I am pasting here because these may also be the same but I am not sure.....

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1f9f98]
goroutine 409 [running]:
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).RemoveConsumer(0x40001b1110, {0x7cc8a0?, 0x40001aafc0})
	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:111 +0x138
github.com/AlexxIT/go2rtc/cmd/webrtc.offerHandler.func1({0x60b620?, 0xb70850?})
	github.com/AlexxIT/go2rtc/cmd/webrtc/webrtc.go:89 +0x74
github.com/AlexxIT/go2rtc/pkg/streamer.(*Element).Fire(...)
	github.com/AlexxIT/go2rtc/pkg/streamer/streamer.go:27
github.com/AlexxIT/go2rtc/pkg/webrtc.(*Conn).Init.func3(0x6)
	github.com/AlexxIT/go2rtc/pkg/webrtc/conn.go:75 +0x6c
created by github.com/pion/webrtc/v3.(*PeerConnection).onConnectionStateChange
	github.com/pion/webrtc/v3@v3.1.43/peerconnection.go:492 +0x17c
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1f9f98]
goroutine 409 [running]:
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).RemoveConsumer(0x40001b1110, {0x7cc8a0?, 0x40001aafc0})
	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:111 +0x138
github.com/AlexxIT/go2rtc/cmd/webrtc.offerHandler.func1({0x60b620?, 0xb70850?})
	github.com/AlexxIT/go2rtc/cmd/webrtc/webrtc.go:89 +0x74
github.com/AlexxIT/go2rtc/pkg/streamer.(*Element).Fire(...)
	github.com/AlexxIT/go2rtc/pkg/streamer/streamer.go:27
github.com/AlexxIT/go2rtc/pkg/webrtc.(*Conn).Init.func3(0x6)
	github.com/AlexxIT/go2rtc/pkg/webrtc/conn.go:75 +0x6c
created by github.com/pion/webrtc/v3.(*PeerConnection).onConnectionStateChange
	github.com/pion/webrtc/v3@v3.1.43/peerconnection.go:492 +0x17c
```

**Comment by calisro** [comment]
@AlexxIT still seeing this on beta 4.

```
*rtp.Header)(0x40007a7630)}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1fa0b8]
goroutine 257 [running]:
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).RemoveConsumer(0x40001af1a0, {0x795a68?, 0x4000a35880})
	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:111 +0x138
github.com/AlexxIT/go2rtc/cmd/webrtc.offerHandler.func1({0x5dac20?, 0xb106d0?})
	github.com/AlexxIT/go2rtc/cmd/webrtc/webrtc.go:89 +0x74
github.com/AlexxIT/go2rtc/pkg/streamer.(*Element).Fire(...)
	github.com/AlexxIT/go2rtc/pkg/streamer/streamer.go:27
github.com/AlexxIT/go2rtc/pkg/webrtc.(*Conn).Init.func3(0x6)
	github.com/AlexxIT/go2rtc/pkg/webrtc/conn.go:75 +0x6c
created by github.com/pion/webrtc/v3.(*PeerConnection).onConnectionStateChange
	github.com/pion/webrtc/v3@v3.1.43/peerconnection.go:492 +0x17c
```

**Comment by AlexxIT** [comment]
This known problem is not fixed yet

**Comment by AlexxIT** [comment]
Should be fixed in v0.1-beta.10

**Comment by AlexxIT** [comment]
Similar problem

```
panic: runtime error: slice bounds out of range [1:0]

goroutine 103 [running]:
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).removeConsumer(0xc00009eea0, 0x0)
	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:192 +0x37e
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).RemoveConsumer(0xc00009eea0, {0x1795fb8, 0xc0000c0070})
	github.com/AlexxIT/go2rtc/cmd/streams/stream.go:119 +0x46d
github.com/AlexxIT/go2rtc/cmd/webrtc.offerHandler.func1({0x163f260, 0x1b72170})
	github.com/AlexxIT/go2rtc/cmd/webrtc/webrtc.go:93 +0xe7
github.com/AlexxIT/go2rtc/pkg/streamer.(*Element).Fire(0xc0000c0070, {0x163f260, 0x1b72170})
	github.com/AlexxIT/go2rtc/pkg/streamer/streamer.go:27 +0x8e
github.com/AlexxIT/go2rtc/pkg/webrtc.(*Conn).Init.func3(0x6)
	github.com/AlexxIT/go2rtc/pkg/webrtc/conn.go:74 +0x58
created by github.com/pion/webrtc/v3.(*PeerConnection).onConnectionStateChange
	github.com/pion/webrtc/v3@v3.1.43/peerconnection.go:492 +0x238
```

**Comment by AlexxIT** [comment]
Should be fixed in https://github.com/AlexxIT/go2rtc/releases/tag/v0.1-rc.1
