### ISSUE TITLE
Segfault when openening up usb camera stream

### ISSUE THREAD

**Issue by parttimer777** [AlexxIT/go2rtc#346]
Hi all,

I'm using go2rtc as part of the frigate docker. When accessing the camera stream it segfaults. It doesn't show up under "devices" but the camera was verified to work when configured in frigate (`- path: /dev/video0`). 

Just checking if anyone has any suggestions or things i can try. I'm on the latest go2rtc release v1.3.1.

The camera is an old Logitech QuickCam Messenger, if that matters.

Thank you

**Docker-compose.yml**
```   
devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/video0:/dev/video0
```

**Error:**

```
22:01:23.331 TRC [ffmpeg] bus
22:01:23.331 TRC [ffmpeg] core
22:01:23.331 TRC [ffmpeg] fd
22:01:23.331 TRC [ffmpeg] full
22:01:23.331 TRC [ffmpeg] mqueue
22:01:23.331 TRC [ffmpeg] null
22:01:23.331 TRC [ffmpeg] nvidia-uvm
22:01:23.331 TRC [ffmpeg] nvidia-uvm-tools
22:01:23.331 TRC [ffmpeg] nvidia0
22:01:23.331 TRC [ffmpeg] nvidiactl
22:01:23.331 TRC [ffmpeg] ptmx
22:01:23.331 TRC [ffmpeg] pts
22:01:23.331 TRC [ffmpeg] random
22:01:23.331 TRC [ffmpeg] shm
22:01:23.331 TRC [ffmpeg] stderr
22:01:23.331 TRC [ffmpeg] stdin
22:01:23.331 TRC [ffmpeg] stdout
22:01:23.331 TRC [ffmpeg] tty
22:01:23.331 TRC [ffmpeg] urandom
22:01:23.331 TRC [ffmpeg] video0
22:01:23.336 TRC [ffmpeg] zero
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x820cc7]

goroutine 204 [running]:
github.com/AlexxIT/go2rtc/cmd/ffmpeg/device.deviceInputSuffix(...)
    github.com/AlexxIT/go2rtc/cmd/ffmpeg/device/device_linux.go:16
github.com/AlexxIT/go2rtc/cmd/ffmpeg/device.GetInput({0xc00003c887, 0x21})
    github.com/AlexxIT/go2rtc/cmd/ffmpeg/device/devices.go:47 +0x467
github.com/AlexxIT/go2rtc/cmd/ffmpeg.parseArgs({0xc00003c887, 0x39})
    github.com/AlexxIT/go2rtc/cmd/ffmpeg/ffmpeg.go:172 +0x55e
github.com/AlexxIT/go2rtc/cmd/ffmpeg.Init.func1({0xc00003c880?, 0x40?})
    github.com/AlexxIT/go2rtc/cmd/ffmpeg/ffmpeg.go:31 +0x46
github.com/AlexxIT/go2rtc/cmd/streams.GetProducer({0xc00003c880, 0x40})
    github.com/AlexxIT/go2rtc/cmd/streams/handlers.go:40 +0x3e
github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).Dial(0xc0001f80a0)
    github.com/AlexxIT/go2rtc/cmd/streams/producer.go:45 +0xab
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc0001d04c0, {0xd46690, 0xc000212080})
    github.com/AlexxIT/go2rtc/cmd/streams/stream.go:64 +0x488
github.com/AlexxIT/go2rtc/cmd/mp4.handlerWSMSE(0xc0000920f0, 0xc000640000)
    github.com/AlexxIT/go2rtc/cmd/mp4/ws.go:36 +0x310
github.com/AlexxIT/go2rtc/cmd/api.apiWS.func2()
    github.com/AlexxIT/go2rtc/cmd/api/ws.go:111 +0x3f
created by github.com/AlexxIT/go2rtc/cmd/api.apiWS
    github.com/AlexxIT/go2rtc/cmd/api/ws.go:110 +0x398
```

**go2rtc config:**
```
api:
  origin: '*'
log:
  format: text
rtsp:
  default_query: mp4
streams:
  pi_cam:
  webcam: ffmpeg:device?video=0&resolution=640x480#video=h264#framerate=30
webrtc:
  candidates:
  - stun:8555
```

**Comment by AlexxIT** [comment]
Can you enter docker container and run:
```
ffmpeg -hide_banner -f v4l2 -list_formats all -i /dev/video0
```

**Comment by parttimer777** [comment]
Hi AlexxIT,

I switched to a newer logitech (4k BRIO) which appears in the go2rtc devices. Also it no longer segfaults.

I returned the old quickcam to it's original owner.

**Comment by parttimer777** [comment]
This worked:

ffmpeg:device?video=0&resolution=1920x1080#video=h264#raw=-pix_fmt yuv420p
