### ISSUE TITLE
Webcam / panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [AlexxIT/go2rtc#355]
panic: runtime error: invalid memory address or nil pointer dereference

The configuration below works perfectly when I use another webcam.
When I try to access the video from another webcam I get an error, and the server stops
to work.

0 ) Configuration

cat go2rtc.yaml

streams:
  webcam: ffmpeg:device?video=2&resolution=1280x720#video=h264#raw=-pix_fmt yuv420p
log:
  format: ""
  level: "info"
  exec: trace

1 ) Information 

ffmpeg -hide_banner -f v4l2 -list_formats all -i /dev/video2

[video4linux2,v4l2 @ 0x55f6750d5140] Raw       :     yuyv422 :           YUYV 4:2:2 : 1920x1080 1680x1050 1600x1200 1600x900 1440x900 1280x1024 1280x960 1280x800 1280x768 1280x720 1280x600 1024x768 960x540 800x600 720x576 720x540 720x480 720x404 720x288 720x240 640x480 640x360 352x288 320x240
/dev/video2: Immediate exit requested

v4l2-ctl --list-devices

USB3.0 Capture Box: UC3200D Vid (usb-0000:00:14.0-2):
        /dev/video2
        /dev/video3
        /dev/media1
USB3.0 Capture Box: UC3200D Vid (usb-0000:00:14.0-2):
        /dev/video2
        /dev/video3
        /dev/media1
		
2 ) Information

v4l2-ctl -d /dev/video2 --list-formats
ioctl: VIDIOC_ENUM_FMT
        Type: Video Capture

        [0]: 'YUYV' (YUYV 4:2:2)

3 ) Information

ffprobe /dev/video2
ffprobe version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
[video4linux2,v4l2 @ 0x555c117b7940] Dequeued v4l2 buffer contains corrupted data (0 bytes).
Input #0, video4linux2,v4l2, from '/dev/video2':
  Duration: N/A, start: 0.000000, bitrate: 884736 kb/s
  Stream #0:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 1280x720, 884736 kb/s, 60 fps, 60 tbr, 1000k tbn, 1000k tbc  
  
 4 ) Information
 
18:26:00.569 INF go2rtc version 1.3.1 linux/amd64
18:26:00.569 INF [api] listen addr=:1984
18:26:00.569 INF [rtsp] listen addr=:8554
18:26:00.569 INF [srtp] listen addr=:8443
18:26:00.569 INF [webrtc] listen addr=:8555/tcp
18:26:04.353 TRC [ffmpeg] acpi_thermal_rel
18:26:04.353 TRC [ffmpeg] autofs
18:26:04.353 TRC [ffmpeg] block
18:26:04.353 TRC [ffmpeg] bsg
18:26:04.353 TRC [ffmpeg] btrfs-control
18:26:04.353 TRC [ffmpeg] bus
18:26:04.353 TRC [ffmpeg] char
18:26:04.353 TRC [ffmpeg] console
18:26:04.353 TRC [ffmpeg] core
18:26:04.353 TRC [ffmpeg] cpu
18:26:04.353 TRC [ffmpeg] cpu_dma_latency
18:26:04.353 TRC [ffmpeg] cuse
18:26:04.353 TRC [ffmpeg] disk
18:26:04.353 TRC [ffmpeg] dma_heap
18:26:04.353 TRC [ffmpeg] dri
18:26:04.353 TRC [ffmpeg] drm_dp_aux0
18:26:04.353 TRC [ffmpeg] drm_dp_aux1
18:26:04.353 TRC [ffmpeg] ecryptfs
18:26:04.353 TRC [ffmpeg] fb0
18:26:04.353 TRC [ffmpeg] fd
18:26:04.353 TRC [ffmpeg] full
18:26:04.353 TRC [ffmpeg] fuse
18:26:04.353 TRC [ffmpeg] gpiochip0
18:26:04.353 TRC [ffmpeg] hidraw0
18:26:04.353 TRC [ffmpeg] hpet
18:26:04.353 TRC [ffmpeg] hugepages
18:26:04.353 TRC [ffmpeg] hwrng
18:26:04.353 TRC [ffmpeg] i2c-0
18:26:04.353 TRC [ffmpeg] i2c-1
18:26:04.353 TRC [ffmpeg] i2c-10
18:26:04.353 TRC [ffmpeg] i2c-11
18:26:04.353 TRC [ffmpeg] i2c-2
18:26:04.353 TRC [ffmpeg] i2c-3
18:26:04.353 TRC [ffmpeg] i2c-4
18:26:04.353 TRC [ffmpeg] i2c-5
18:26:04.353 TRC [ffmpeg] i2c-6
18:26:04.353 TRC [ffmpeg] i2c-7
18:26:04.353 TRC [ffmpeg] i2c-8
18:26:04.353 TRC [ffmpeg] i2c-9
18:26:04.353 TRC [ffmpeg] initctl
18:26:04.353 TRC [ffmpeg] input
18:26:04.353 TRC [ffmpeg] kmsg
18:26:04.353 TRC [ffmpeg] kvm
18:26:04.353 TRC [ffmpeg] log
18:26:04.353 TRC [ffmpeg] loop-control
18:26:04.353 TRC [ffmpeg] loop0
18:26:04.353 TRC [ffmpeg] loop1
18:26:04.353 TRC [ffmpeg] loop10
18:26:04.353 TRC [ffmpeg] loop11
18:26:04.353 TRC [ffmpeg] loop12
18:26:04.353 TRC [ffmpeg] loop13
18:26:04.353 TRC [ffmpeg] loop14
18:26:04.353 TRC [ffmpeg] loop15
18:26:04.353 TRC [ffmpeg] loop16
18:26:04.353 TRC [ffmpeg] loop17
18:26:04.353 TRC [ffmpeg] loop18
18:26:04.353 TRC [ffmpeg] loop2
18:26:04.353 TRC [ffmpeg] loop3
18:26:04.353 TRC [ffmpeg] loop4
18:26:04.353 TRC [ffmpeg] loop5
18:26:04.353 TRC [ffmpeg] loop6
18:26:04.353 TRC [ffmpeg] loop7
18:26:04.353 TRC [ffmpeg] loop8
18:26:04.353 TRC [ffmpeg] loop9
18:26:04.353 TRC [ffmpeg] mapper
18:26:04.353 TRC [ffmpeg] mcelog
18:26:04.353 TRC [ffmpeg] media0
18:26:04.353 TRC [ffmpeg] media1
18:26:04.353 TRC [ffmpeg] mei0
18:26:04.353 TRC [ffmpeg] mem
18:26:04.353 TRC [ffmpeg] mqueue
18:26:04.353 TRC [ffmpeg] mtd0
18:26:04.353 TRC [ffmpeg] mtd0ro
18:26:04.353 TRC [ffmpeg] net
18:26:04.353 TRC [ffmpeg] null
18:26:04.353 TRC [ffmpeg] nvram
18:26:04.353 TRC [ffmpeg] port
18:26:04.353 TRC [ffmpeg] ppp
18:26:04.353 TRC [ffmpeg] psaux
18:26:04.353 TRC [ffmpeg] ptmx
18:26:04.353 TRC [ffmpeg] pts
18:26:04.353 TRC [ffmpeg] random
18:26:04.353 TRC [ffmpeg] rfkill
18:26:04.353 TRC [ffmpeg] rtc
18:26:04.353 TRC [ffmpeg] rtc0
18:26:04.353 TRC [ffmpeg] sda
18:26:04.353 TRC [ffmpeg] sda1
18:26:04.353 TRC [ffmpeg] sda2
18:26:04.353 TRC [ffmpeg] sg0
18:26:04.353 TRC [ffmpeg] shm
18:26:04.353 TRC [ffmpeg] snapshot
18:26:04.353 TRC [ffmpeg] snd
18:26:04.353 TRC [ffmpeg] stderr
18:26:04.353 TRC [ffmpeg] stdin
18:26:04.353 TRC [ffmpeg] stdout
18:26:04.353 TRC [ffmpeg] tpm0
18:26:04.353 TRC [ffmpeg] tpmrm0
18:26:04.353 TRC [ffmpeg] tty
18:26:04.353 TRC [ffmpeg] tty0
18:26:04.353 TRC [ffmpeg] tty1
18:26:04.353 TRC [ffmpeg] tty10
18:26:04.353 TRC [ffmpeg] tty11
18:26:04.353 TRC [ffmpeg] tty12
18:26:04.353 TRC [ffmpeg] tty13
18:26:04.353 TRC [ffmpeg] tty14
18:26:04.353 TRC [ffmpeg] tty15
18:26:04.353 TRC [ffmpeg] tty16
18:26:04.353 TRC [ffmpeg] tty17
18:26:04.353 TRC [ffmpeg] tty18
18:26:04.353 TRC [ffmpeg] tty19
18:26:04.353 TRC [ffmpeg] tty2
18:26:04.353 TRC [ffmpeg] tty20
18:26:04.353 TRC [ffmpeg] tty21
18:26:04.353 TRC [ffmpeg] tty22
18:26:04.353 TRC [ffmpeg] tty23
18:26:04.353 TRC [ffmpeg] tty24
18:26:04.353 TRC [ffmpeg] tty25
18:26:04.353 TRC [ffmpeg] tty26
18:26:04.353 TRC [ffmpeg] tty27
18:26:04.353 TRC [ffmpeg] tty28
18:26:04.353 TRC [ffmpeg] tty29
18:26:04.353 TRC [ffmpeg] tty3
18:26:04.353 TRC [ffmpeg] tty30
18:26:04.353 TRC [ffmpeg] tty31
18:26:04.354 TRC [ffmpeg] tty32
18:26:04.354 TRC [ffmpeg] tty33
18:26:04.354 TRC [ffmpeg] tty34
18:26:04.354 TRC [ffmpeg] tty35
18:26:04.354 TRC [ffmpeg] tty36
18:26:04.354 TRC [ffmpeg] tty37
18:26:04.354 TRC [ffmpeg] tty38
18:26:04.354 TRC [ffmpeg] tty39
18:26:04.354 TRC [ffmpeg] tty4
18:26:04.354 TRC [ffmpeg] tty40
18:26:04.354 TRC [ffmpeg] tty41
18:26:04.354 TRC [ffmpeg] tty42
18:26:04.354 TRC [ffmpeg] tty43
18:26:04.354 TRC [ffmpeg] tty44
18:26:04.354 TRC [ffmpeg] tty45
18:26:04.354 TRC [ffmpeg] tty46
18:26:04.354 TRC [ffmpeg] tty47
18:26:04.354 TRC [ffmpeg] tty48
18:26:04.354 TRC [ffmpeg] tty49
18:26:04.354 TRC [ffmpeg] tty5
18:26:04.354 TRC [ffmpeg] tty50
18:26:04.354 TRC [ffmpeg] tty51
18:26:04.354 TRC [ffmpeg] tty52
18:26:04.354 TRC [ffmpeg] tty53
18:26:04.354 TRC [ffmpeg] tty54
18:26:04.354 TRC [ffmpeg] tty55
18:26:04.354 TRC [ffmpeg] tty56
18:26:04.354 TRC [ffmpeg] tty57
18:26:04.354 TRC [ffmpeg] tty58
18:26:04.354 TRC [ffmpeg] tty59
18:26:04.354 TRC [ffmpeg] tty6
18:26:04.354 TRC [ffmpeg] tty60
18:26:04.354 TRC [ffmpeg] tty61
18:26:04.354 TRC [ffmpeg] tty62
18:26:04.354 TRC [ffmpeg] tty63
18:26:04.354 TRC [ffmpeg] tty7
18:26:04.354 TRC [ffmpeg] tty8
18:26:04.354 TRC [ffmpeg] tty9
18:26:04.354 TRC [ffmpeg] ttyS0
18:26:04.354 TRC [ffmpeg] ttyS1
18:26:04.354 TRC [ffmpeg] ttyS10
18:26:04.354 TRC [ffmpeg] ttyS11
18:26:04.354 TRC [ffmpeg] ttyS12
18:26:04.354 TRC [ffmpeg] ttyS13
18:26:04.354 TRC [ffmpeg] ttyS14
18:26:04.354 TRC [ffmpeg] ttyS15
18:26:04.354 TRC [ffmpeg] ttyS16
18:26:04.354 TRC [ffmpeg] ttyS17
18:26:04.354 TRC [ffmpeg] ttyS18
18:26:04.354 TRC [ffmpeg] ttyS19
18:26:04.354 TRC [ffmpeg] ttyS2
18:26:04.354 TRC [ffmpeg] ttyS20
18:26:04.354 TRC [ffmpeg] ttyS21
18:26:04.354 TRC [ffmpeg] ttyS22
18:26:04.354 TRC [ffmpeg] ttyS23
18:26:04.354 TRC [ffmpeg] ttyS24
18:26:04.354 TRC [ffmpeg] ttyS25
18:26:04.354 TRC [ffmpeg] ttyS26
18:26:04.354 TRC [ffmpeg] ttyS27
18:26:04.354 TRC [ffmpeg] ttyS28
18:26:04.354 TRC [ffmpeg] ttyS29
18:26:04.354 TRC [ffmpeg] ttyS3
18:26:04.354 TRC [ffmpeg] ttyS30
18:26:04.354 TRC [ffmpeg] ttyS31
18:26:04.354 TRC [ffmpeg] ttyS4
18:26:04.354 TRC [ffmpeg] ttyS5
18:26:04.354 TRC [ffmpeg] ttyS6
18:26:04.354 TRC [ffmpeg] ttyS7
18:26:04.354 TRC [ffmpeg] ttyS8
18:26:04.354 TRC [ffmpeg] ttyS9
18:26:04.354 TRC [ffmpeg] ttyprintk
18:26:04.354 TRC [ffmpeg] udmabuf
18:26:04.354 TRC [ffmpeg] uhid
18:26:04.354 TRC [ffmpeg] uinput
18:26:04.354 TRC [ffmpeg] urandom
18:26:04.354 TRC [ffmpeg] usb
18:26:04.354 TRC [ffmpeg] userio
18:26:04.354 TRC [ffmpeg] v4l
18:26:04.354 TRC [ffmpeg] vcs
18:26:04.354 TRC [ffmpeg] vcs1
18:26:04.354 TRC [ffmpeg] vcs2
18:26:04.354 TRC [ffmpeg] vcs3
18:26:04.354 TRC [ffmpeg] vcs4
18:26:04.354 TRC [ffmpeg] vcs5
18:26:04.354 TRC [ffmpeg] vcs6
18:26:04.354 TRC [ffmpeg] vcsa
18:26:04.354 TRC [ffmpeg] vcsa1
18:26:04.354 TRC [ffmpeg] vcsa2
18:26:04.354 TRC [ffmpeg] vcsa3
18:26:04.354 TRC [ffmpeg] vcsa4
18:26:04.354 TRC [ffmpeg] vcsa5
18:26:04.354 TRC [ffmpeg] vcsa6
18:26:04.354 TRC [ffmpeg] vcsu
18:26:04.354 TRC [ffmpeg] vcsu1
18:26:04.354 TRC [ffmpeg] vcsu2
18:26:04.354 TRC [ffmpeg] vcsu3
18:26:04.354 TRC [ffmpeg] vcsu4
18:26:04.354 TRC [ffmpeg] vcsu5
18:26:04.354 TRC [ffmpeg] vcsu6
18:26:04.354 TRC [ffmpeg] vfio
18:26:04.354 TRC [ffmpeg] vga_arbiter
18:26:04.354 TRC [ffmpeg] vhci
18:26:04.354 TRC [ffmpeg] vhost-net
18:26:04.354 TRC [ffmpeg] vhost-vsock
18:26:04.354 TRC [ffmpeg] video0
18:26:04.654 TRC [ffmpeg] video1
18:26:04.688 TRC [ffmpeg] video2
18:26:04.814 TRC [ffmpeg] video3
18:26:04.848 TRC [ffmpeg] wmi
18:26:04.848 TRC [ffmpeg] zero
18:26:04.848 TRC [ffmpeg] zfs
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x820cc7]

goroutine 37 [running]:
github.com/AlexxIT/go2rtc/cmd/ffmpeg/device.deviceInputSuffix(...)
        github.com/AlexxIT/go2rtc/cmd/ffmpeg/device/device_linux.go:16
github.com/AlexxIT/go2rtc/cmd/ffmpeg/device.GetInput({0xc0000c0377, 0x22})
        github.com/AlexxIT/go2rtc/cmd/ffmpeg/device/devices.go:47 +0x467
github.com/AlexxIT/go2rtc/cmd/ffmpeg.parseArgs({0xc0000c0377, 0x42})
        github.com/AlexxIT/go2rtc/cmd/ffmpeg/ffmpeg.go:172 +0x55e
github.com/AlexxIT/go2rtc/cmd/ffmpeg.Init.func1({0xc0000c0370?, 0x49?})
        github.com/AlexxIT/go2rtc/cmd/ffmpeg/ffmpeg.go:31 +0x46
github.com/AlexxIT/go2rtc/cmd/streams.GetProducer({0xc0000c0370, 0x49})
        github.com/AlexxIT/go2rtc/cmd/streams/handlers.go:40 +0x3e
github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).Dial(0xc0001e2a00)
        github.com/AlexxIT/go2rtc/cmd/streams/producer.go:45 +0xab
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc0001d43c0, {0xd46720, 0xc00013a380})
        github.com/AlexxIT/go2rtc/cmd/streams/stream.go:64 +0x488
github.com/AlexxIT/go2rtc/cmd/webrtc.asyncHandler(0xc00011e320, 0xc000123680)
        github.com/AlexxIT/go2rtc/cmd/webrtc/init.go:162 +0x685
github.com/AlexxIT/go2rtc/cmd/api.apiWS.func2()
        github.com/AlexxIT/go2rtc/cmd/api/ws.go:111 +0x3f
created by github.com/AlexxIT/go2rtc/cmd/api.apiWS
        github.com/AlexxIT/go2rtc/cmd/api/ws.go:110 +0x398
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x820cc7]

goroutine 47 [running]:
github.com/AlexxIT/go2rtc/cmd/ffmpeg/device.deviceInputSuffix(...)
        github.com/AlexxIT/go2rtc/cmd/ffmpeg/device/device_linux.go:16
github.com/AlexxIT/go2rtc/cmd/ffmpeg/device.GetInput({0xc0000c0377, 0x22})
        github.com/AlexxIT/go2rtc/cmd/ffmpeg/device/devices.go:47 +0x467
github.com/AlexxIT/go2rtc/cmd/ffmpeg.parseArgs({0xc0000c0377, 0x42})
        github.com/AlexxIT/go2rtc/cmd/ffmpeg/ffmpeg.go:172 +0x55e
github.com/AlexxIT/go2rtc/cmd/ffmpeg.Init.func1({0xc0000c0370?, 0x49?})
        github.com/AlexxIT/go2rtc/cmd/ffmpeg/ffmpeg.go:31 +0x46
github.com/AlexxIT/go2rtc/cmd/streams.GetProducer({0xc0000c0370, 0x49})
        github.com/AlexxIT/go2rtc/cmd/streams/handlers.go:40 +0x3e
github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).Dial(0xc0001e2a00)
        github.com/AlexxIT/go2rtc/cmd/streams/producer.go:45 +0xab
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc0001d43c0, {0xd46690, 0xc00030e000})
        github.com/AlexxIT/go2rtc/cmd/streams/stream.go:64 +0x488
github.com/AlexxIT/go2rtc/cmd/mp4.handlerWSMSE(0xc00011e320, 0xc0001236c0)
        github.com/AlexxIT/go2rtc/cmd/mp4/ws.go:36 +0x310
github.com/AlexxIT/go2rtc/cmd/api.apiWS.func2()
        github.com/AlexxIT/go2rtc/cmd/api/ws.go:111 +0x3f
created by github.com/AlexxIT/go2rtc/cmd/api.apiWS
        github.com/AlexxIT/go2rtc/cmd/api/ws.go:110 +0x398

**Comment by andersondeoliveiramachado** [comment]
![image](https://user-images.githubusercontent.com/1152426/232254338-2a6bdcb1-e685-48fa-9ce0-6ec154c8bf3e.png)

**Comment by AlexxIT** [comment]
Can you show output:
```
ffmpeg -hide_banner -f v4l2 -list_formats all -i /dev/video0
```

**Comment by AlexxIT** [comment]
It's strange. Because check is very simple
https://github.com/AlexxIT/go2rtc/blob/fd580b6f2c35bf77d5a9095e7da445ad49cd5b3a/cmd/ffmpeg/device/device_linux.go#L35-L48

You have `Raw` word in output from `ffmpeg -hide_banner -f v4l2 -list_formats all -i /dev/video2`.

Maybe some problems with linux rights?

**Comment by andersondeoliveiramachado** [comment]
What I realized now performing more tests that the problem only happens when I have more than one webcam connected. For example :

/dev/video0
/dev/video1

/dev/video2
/dev/video3

**Comment by andersondeoliveiramachado** [comment]
> Can you see all 4 devices in go2rtc WebUI add page?

Not just two.
 
/dev/diveo0 

/dev/diveo2

**Comment by AlexxIT** [comment]
@andersondeoliveiramachado that's why you have panic.
`device?video=2` mean 3rd source, but you have only two.
