### ISSUE TITLE
Fix RTSP server close (panic) without client request

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/go2rtc#364]
```
Creating go2rtc ... done
01:02:47.821 INF go2rtc version 1.3.2 linux/amd64
01:02:47.821 INF [api] listen addr=:1984
01:02:47.821 INF [rtsp] listen addr=:8554
01:02:47.822 INF [srtp] listen addr=:8443
01:02:47.822 INF [webrtc] listen addr=:8555

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x674e40]

goroutine 5 [running]:
net/url.(*URL).String(0x0)
        net/url/url.go:810 +0x40
github.com/AlexxIT/go2rtc/pkg/tcp.(*Request).String(0xc00007e050)
        github.com/AlexxIT/go2rtc/pkg/tcp/textproto.go:96 +0x3d
github.com/AlexxIT/go2rtc/pkg/tcp.(*Request).Write(0xc10791e7affed6d0?, {0xd43780, 0xc000012010})
        github.com/AlexxIT/go2rtc/pkg/tcp/textproto.go:108 +0x25
github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).WriteRequest(0xc0000ac000, 0xc00007e050)
        github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:291 +0x456
github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Teardown(...)
        github.com/AlexxIT/go2rtc/pkg/rtsp/client.go:287
github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Close(0xc0000ac000)
        github.com/AlexxIT/go2rtc/pkg/rtsp/client.go:291 +0x65
github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler(0xc0000ac000)
        github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:223 +0x237
created by github.com/AlexxIT/go2rtc/cmd/rtsp.Init.func1
        github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:74 +0x48
```

From https://github.com/AlexxIT/go2rtc/issues/355#issuecomment-1512207003

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.4.0
