### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by nejcmedved** [AlexxIT/go2rtc#390]
Hi,

I have an issue with getting error when I try to open mp4 stream

http://{go2rtcip}:1984/stream.html?src={camera_name}

error says: 

```
panic: runtime error: index out of range [0] with length 0

goroutine 391 [running]:
github.com/deepch/vdk/codec/h265parser.AVCDecoderConfRecord.Marshal({0x1, 0x60, 0x0, 0x3, {0xc0002ed038, 0x1, 0x1}, {0xc0002eccc0, 0x1, 0x1}, ...}, ...)
        github.com/deepch/vdk@v0.0.19/codec/h265parser/parser.go:634 +0x65c
github.com/deepch/vdk/codec/h265parser.NewCodecDataFromVPSAndSPSAndPPS({_, _, _}, {_, _, _}, {_, _, _})
        github.com/deepch/vdk@v0.0.19/codec/h265parser/parser.go:515 +0x425
github.com/AlexxIT/go2rtc/pkg/mp4.(*Muxer).GetInit(0xc00101ee10, {0xc000431678, 0x1, 0x1?})
        github.com/AlexxIT/go2rtc/pkg/mp4/muxer.go:93 +0x3bb
github.com/AlexxIT/go2rtc/pkg/mp4.(*Consumer).Init(0xc0002a67e0)
        github.com/AlexxIT/go2rtc/pkg/mp4/consumer.go:181 +0xcd
github.com/AlexxIT/go2rtc/cmd/mp4.handlerWSMSE(0xc00101ed20, 0xc000515860)
        github.com/AlexxIT/go2rtc/cmd/mp4/ws.go:47 +0x4b2
github.com/AlexxIT/go2rtc/cmd/api.apiWS.func2()
        github.com/AlexxIT/go2rtc/cmd/api/ws.go:111 +0x3f
created by github.com/AlexxIT/go2rtc/cmd/api.apiWS
        github.com/AlexxIT/go2rtc/cmd/api/ws.go:110 +0x398
```

I am using version 1.4.0

The issue is appearing only on one or two out of 20 cameras.

Thanks for help in advance,

Nejc

**Comment by AlexxIT** [comment]
I think problem same #384
You can try latest master version

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.5.0

**Comment by nejcmedved** [comment]
Hi,

we have tried latest master docker image this morning. Works great!

Thanks for solving, Nejc
