### ISSUE TITLE
Crash after update to 1.5.0

### ISSUE THREAD

**Issue by Heronimonimo** [AlexxIT/go2rtc#411]
go2rtc add-on crashes after update to 1.5.0 on a HA OS system running on Proxmox. Log below.

```
runtime.throw({0xc4e331?, 0x12?})
	runtime/panic.go:1047 +0x5d fp=0xc0000ba9c0 sp=0xc0000ba990 pc=0x436c9d
runtime.(*mcache).allocLarge(0x4?, 0xffffe0c800000000, 0x1)
	runtime/mcache.go:236 +0x179 fp=0xc0000baa08 sp=0xc0000ba9c0 pc=0x416b99
runtime.mallocgc(0xffffe0c800000000, 0xbfbc20, 0x1)
	runtime/malloc.go:1053 +0x4fe fp=0xc0000baa70 sp=0xc0000baa08 pc=0x40d99e
runtime.newobject(0xc0000c0900?)
	runtime/malloc.go:1254 +0x27 fp=0xc0000baa98 sp=0xc0000baa70 pc=0x40de87
text/template/parse.(*Tree).newCommand(...)
	text/template/parse/node.go:299
text/template/parse.(*Tree).command(0xc0000c0900)
	text/template/parse/parse.go:689 +0xa7 fp=0xc0000baba8 sp=0xc0000baa98 pc=0x9a1fa7
text/template/parse.(*Tree).pipeline(0xc0000c0900, {0xc46971, 0x5}, 0x10)
	text/template/parse/parse.go:502 +0x859 fp=0xc0000baf60 sp=0xc0000baba8 pc=0x9a0419
text/template/parse.(*Tree).parseControl(0xc0000c0900, 0x0, {0xc46971, 0x5})
	text/template/parse/parse.go:526 +0xef fp=0xc0000bb090 sp=0xc0000baf60 pc=0x9a0c8f
text/template/parse.(*Tree).rangeControl(0xc0000c0900)
	text/template/parse/parse.go:580 +0x30 fp=0xc0000bb0e8 sp=0xc0000bb090 pc=0x9a1210
text/template/parse.(*Tree).action(0xc0000c0900)
	text/template/parse/parse.go:409 +0x2a5 fp=0xc0000bb250 sp=0xc0000bb0e8 pc=0x99f625
text/template/parse.(*Tree).textOrAction(0xc0000c0900)
	text/template/parse/parse.go:374 +0x2bc fp=0xc0000bb380 sp=0xc0000bb250 pc=0x99f19c
text/template/parse.(*Tree).parse(0xc0000c0900)
	text/template/parse/parse.go:315 +0x309 fp=0xc0000bb570 sp=0xc0000bb380 pc=0x99e6c9
text/template/parse.(*Tree).Parse(0xc0000c0900, {0xc7c466, 0x172}, {0x0?, 0xc0000bb688?}, {0x0?, 0x10?}, 0xb40b80?, {0xc0000f05a0, 0x2, ...})
	text/template/parse/parse.go:251 +0x28a fp=0xc0000bb628 sp=0xc0000bb570 pc=0x99deea
text/template/parse.Parse({0xc4a83d, 0x9}, {0xc7c466, 0x172}, {0x0, 0x0}, {0x0, 0x0}, {0xc0000f05a0, 0x2, ...})
	text/template/parse/parse.go:66 +0x130 fp=0xc0000bb698 sp=0xc0000bb628 pc=0x99c970
text/template.(*Template).Parse(0xc00009b4c0, {0xc7c466, 0x172})
	text/template/template.go:210 +0x7ca fp=0xc0000bb788 sp=0xc0000bb698 pc=0x9ac2aa
html/template.(*Template).Parse(0xc0000f6180, {0xc7c466, 0x172})
	html/template/template.go:191 +0x90 fp=0xc0000bb828 sp=0xc0000bb788 pc=0x9b1490
net/rpc.init()
	net/rpc/debug.go:39 +0x87 fp=0xc0000bb860 sp=0xc0000bb828 pc=0x9b8aa7
runtime.doInit(0x11822a0)
	runtime/proc.go:6506 +0x126 fp=0xc0000bb990 sp=0xc0000bb860 pc=0x446c66
runtime.doInit(0x1181f80)
	runtime/proc.go:6483 +0x71 fp=0xc0000bbac0 sp=0xc0000bb990 pc=0x446bb1
runtime.doInit(0x1183340)
	runtime/proc.go:6483 +0x71 fp=0xc0000bbbf0 sp=0xc0000bbac0 pc=0x446bb1
runtime.doInit(0x117cdc0)
	runtime/proc.go:6483 +0x71 fp=0xc0000bbd20 sp=0xc0000bbbf0 pc=0x446bb1
runtime.doInit(0x11827a0)
	runtime/proc.go:6483 +0x71 fp=0xc0000bbe50 sp=0xc0000bbd20 pc=0x446bb1
runtime.doInit(0x11855c0)
	runtime/proc.go:6483 +0x71 fp=0xc0000bbf80 sp=0xc0000bbe50 pc=0x446bb1
runtime.main()
	runtime/proc.go:233 +0x1c6 fp=0xc0000bbfe0 sp=0xc0000bbf80 pc=0x439546
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc0000bbfe8 sp=0xc0000bbfe0 pc=0x46c421
goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:381 +0xd6 fp=0xc00005cfb0 sp=0xc00005cf90 pc=0x4399b6
runtime.goparkunlock(...)
	runtime/proc.go:387
runtime.forcegchelper()
	runtime/proc.go:305 +0xb0 fp=0xc00005cfe0 sp=0xc00005cfb0 pc=0x4397f0
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc00005cfe8 sp=0xc00005cfe0 pc=0x46c421
created by runtime.init.6
	runtime/proc.go:293 +0x25
goroutine 3 [GC sweep wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	runtime/proc.go:381 +0xd6 fp=0xc00005d780 sp=0xc00005d760 pc=0x4399b6
runtime.goparkunlock(...)
	runtime/proc.go:387
runtime.bgsweep(0x0?)
	runtime/mgcsweep.go:278 +0x8e fp=0xc00005d7c8 sp=0xc00005d780 pc=0x4241ae
runtime.gcenable.func1()
	runtime/mgc.go:178 +0x26 fp=0xc00005d7e0 sp=0xc00005d7c8 pc=0x419466
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc00005d7e8 sp=0xc00005d7e0 pc=0x46c421
created by runtime.gcenable
	runtime/mgc.go:178 +0x6b
goroutine 4 [GC scavenge wait]:
runtime.gopark(0xc00007c000?, 0xd53588?, 0x1?, 0x0?, 0x0?)
	runtime/proc.go:381 +0xd6 fp=0xc00005df70 sp=0xc00005df50 pc=0x4399b6
runtime.goparkunlock(...)
	runtime/proc.go:387
runtime.(*scavengerState).park(0x11eb040)
	runtime/mgcscavenge.go:400 +0x53 fp=0xc00005dfa0 sp=0xc00005df70 pc=0x4220d3
runtime.bgscavenge(0x0?)
	runtime/mgcscavenge.go:628 +0x45 fp=0xc00005dfc8 sp=0xc00005dfa0 pc=0x4226a5
runtime.gcenable.func2()
	runtime/mgc.go:179 +0x26 fp=0xc00005dfe0 sp=0xc00005dfc8 pc=0x419406
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc00005dfe8 sp=0xc00005dfe0 pc=0x46c421
created by runtime.gcenable
	runtime/mgc.go:179 +0xaa
goroutine 5 [runnable]:
runtime.runfinq()
	runtime/mfinal.go:176 fp=0xc00005c7e0 sp=0xc00005c7d8 pc=0x4183a0
runtime.goexit()
	runtime/asm_amd64.s:1598 +0x1 fp=0xc00005c7e8 sp=0xc00005c7e0 pc=0x46c421
created by runtime.createfing
	runtime/mfinal.go:163 +0x45
```

**Comment by Heronimonimo** [comment]
Rollback to 1.4.0 fixed it for now. No clue what causes this.

**Comment by AlexxIT** [comment]
I can't see any function related to go2rtc code. Maybe log too big and main part cut off. Can you get full version?

**Comment by AlexxIT** [comment]
I can't see anything related to go2rtc in this log

**Comment by Heronimonimo** [comment]
Yes, can't seem to replicate they issue. Now running fine on the newest version.
