### ISSUE TITLE
Camera entity_id configuration usage is broken since 1.3.2

### ISSUE THREAD

**Issue by DeKaN** [AlexxIT/go2rtc#412]
I use WebRTC custom integration in Home Assistant with installed go2rtc as addon
My camera is Ezviz C1C

I used card with this configuration at Lovelace
```
type: custom:webrtc-camera
entity: camera.entity_id_here
```
After updating go2rtc to 1.3.2-1.5.0 version I see `Server disconnected` at card with error in log:
```
2023/05/04 19:01:32 http: panic serving [::1]:39238: runtime error: slice bounds out of range [1:0]
goroutine 103 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1854 +0xbf
panic({0xbfb7c0, 0xc0002720a8})
	runtime/panic.go:890 +0x263
github.com/AlexxIT/go2rtc/internal/streams.NewTemplate({0xc0001021f8, 0x15}, {0xb3bb40?, 0xc00010b938?})
	github.com/AlexxIT/go2rtc/internal/streams/init.go:47 +0x197
github.com/AlexxIT/go2rtc/internal/streams.streamsHandler({0xd5dd10?, 0xc00009c000}, 0xc00017d600)
	github.com/AlexxIT/go2rtc/internal/streams/init.go:113 +0x5ca
net/http.HandlerFunc.ServeHTTP(0xc000090600?, {0xd5dd10?, 0xc00009c000?}, 0x40daaa?)
	net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc0001021f3?, {0xd5dd10, 0xc00009c000}, 0xc00017d600)
	net/http/server.go:2500 +0x149
net/http.serverHandler.ServeHTTP({0xc000199770?}, {0xd5dd10, 0xc00009c000}, 0xc00017d600)
	net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc00017e360, {0xd5e308, 0xc000034120})
	net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	net/http/server.go:3089 +0x5ed
```

As workaround I have to switch to direct url providing
```
type: custom:webrtc-camera
url: 'rtsp://USER:PASS@IP:554/Streaming/Channels/101'
```
or rollback go2rtc to version 1.3.1

**Comment by AlexxIT** [comment]
Do you have something in the go2rtc YAML?

**Comment by DeKaN** [comment]
No, I haven't

**Comment by AlexxIT** [comment]
Similar #474

**Comment by maxcanna** [comment]
same camera, same setup, same problem.
could it be something specific?

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.0
