### ISSUE TITLE
runtime error: slice bounds out of range in pcm.RepackBackchannel

### ISSUE THREAD

**Issue by z419** [AlexxIT/go2rtc#432]
```
panic: runtime error: slice bounds out of range [1024:256]

goroutine 172 [running]:
github.com/AlexxIT/go2rtc/pkg/pcm.RepackBackchannel.func1(0xc0001ba850)
	github.com/AlexxIT/go2rtc/pkg/pcm/helpers.go:32 +0x1de
github.com/AlexxIT/go2rtc/pkg/core.(*Sender).HandleRTP.func1()
	github.com/AlexxIT/go2rtc/pkg/core/track.go:137 +0xaa
created by github.com/AlexxIT/go2rtc/pkg/core.(*Sender).HandleRTP
	github.com/AlexxIT/go2rtc/pkg/core/track.go:131 +0x351

[INFO] The go2rtc service exited with code 2 (by signal 0)
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.0
