### ISSUE TITLE
Fix panic after RTSP reconnect feature

### ISSUE THREAD

**Issue by z419** [AlexxIT/go2rtc#433]
```
14:40:34.881 WRN /home/media/build/go2rtc-master/internal/streams/producer.go:159 > error="read tcp 172.22.0.2:41610->192.168.1.123:554: i/o timeout" url=rtsp://...
  14:40:34.894 WRN /home/media/build/go2rtc-master/internal/streams/producer.go:159 > error=EOF url=ffmpeg:x#audio=opus
  panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x81384d]
  
  goroutine 39 [running]:
  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).WriteRequest(0xc0004a2360, 0xc00217f270)
  	/home/media/build/go2rtc-master/pkg/rtsp/conn.go:289 +0x3ed
  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Do(0xc0004a2360, 0xc00217f270)
  	/home/media/build/go2rtc-master/pkg/rtsp/client.go:52 +0x27
  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).SetupMedia(0xc0004a2360, 0xc001d6cb40)
  	/home/media/build/go2rtc-master/pkg/rtsp/client.go:215 +0x328
  github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).GetTrack(0xc0004a2360, 0xc001d6cb40, 0xc000960c00)
  	/home/media/build/go2rtc-master/pkg/rtsp/producer.go:27 +0x1d5
  github.com/AlexxIT/go2rtc/internal/streams.(*Producer).reconnect(0xc000120630, 0x1, 0x0)
  	/home/media/build/go2rtc-master/internal/streams/producer.go:204 +0x807
  github.com/AlexxIT/go2rtc/internal/streams.(*Producer).worker(0xc000120630, {0xd6f378?, 0xc0000aa120?}, 0x1)
  	/home/media/build/go2rtc-master/internal/streams/producer.go:162 +0x15d
  created by github.com/AlexxIT/go2rtc/internal/streams.(*Producer).start
  	/home/media/build/go2rtc-master/internal/streams/producer.go:146 +0x1be
```

Other functions that call c.Fire() may also possibly be affected

**Comment by AlexxIT** [comment]
What go2rtc version?

**Comment by tsightler** [comment]
I have this one that looks similar-ish (although it is an older go2rtc of 1.3.1, I'll update it but thought it might be interesting regardless):

```
WRN github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:214 > error="write tcp 172.30.33.2:8554->172.30.32.1:50312: write:
 broken pipe"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7c665f]

goroutine 111 [running]:
github.com/AlexxIT/go2rtc/cmd/streams.(*Producer).GetMedias(0xc00015c6e0?)
     github.com/AlexxIT/go2rtc/cmd/streams/producer.go:61 +0x9f
github.com/AlexxIT/go2rtc/cmd/streams.(*Stream).AddConsumer(0xc000144380, {0xd466f0, 0xc000222700})
     github.com/AlexxIT/go2rtc/cmd/streams/stream.go:69 +0x4b4
github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler.func1({0xb2e400?, 0xd3ff30?})
     github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:181 +0x5d0
github.com/AlexxIT/go2rtc/pkg/core.(*Listener).Fire(...)
     github.com/AlexxIT/go2rtc/pkg/core/listener.go:16
github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Accept(0xc000222700)
     github.com/AlexxIT/go2rtc/pkg/rtsp/server.go:92 +0xb88
github.com/AlexxIT/go2rtc/cmd/rtsp.tcpHandler(0xc000222700)
     github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:213 +0x1ad
created by github.com/AlexxIT/go2rtc/cmd/rtsp.Init.func1
     github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:72 +0x48
```

**Comment by AlexxIT** [comment]
@tsightler streams GetMedias was already fixed

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.6.0
