### ISSUE TITLE
Panic while MJPEG processing

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/go2rtc#48]
```
11:40:25.812 TRC [api] GET url=/api/stream.mjpeg?src=camera2
11:40:25.812 TRC [streams] consumer:1:0 candidate media="video, recvonly, 0 JPEG/0"
11:40:25.812 TRC [streams] producer:0:0 candidate media="video, sendonly, 26 JPEG/90000"
11:40:25.812 TRC [streams] match producer:0:0 => consumer:1:0 codec="26 JPEG/90000"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5b9f8c]

goroutine 68 [running]:
bufio.(*Writer).Write(0xc000119940, {0xc00071c000, 0x0, 0xc0004f9a00})
        bufio/bufio.go:639 +0xec
net/http.(*response).write(0xc0000941c0, 0x15f9f, {0xc00071c000, 0x15f9f, 0x16000}, {0x0, 0x0})
        net/http/server.go:1593 +0x21e
net/http.(*response).Write(0x0, {0xc00071c000, 0x38, 0xc0000360b0})
        net/http/server.go:1551 +0x30
github.com/AlexxIT/go2rtc/cmd/mjpeg.handler.func1({0xa2a280, 0xc00000c030})
        github.com/AlexxIT/go2rtc/cmd/mjpeg/mjpeg.go:36 +0x1c3
github.com/AlexxIT/go2rtc/pkg/streamer.(*Element).Fire(0xc000706000, {0xa2a280, 0xc00000c030})
        github.com/AlexxIT/go2rtc/pkg/streamer/streamer.go:27 +0x47
github.com/AlexxIT/go2rtc/pkg/mjpeg.(*Consumer).AddTrack.func1(0xc000181810)
        github.com/AlexxIT/go2rtc/pkg/mjpeg/consumer.go:78 +0x44c
github.com/AlexxIT/go2rtc/pkg/streamer.(*Track).WriteRTP(0xc0003fd260, 0xc0003fd230)
        github.com/AlexxIT/go2rtc/pkg/streamer/track.go:28 +0xa4
github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Handle(0xc000308000)
        github.com/AlexxIT/go2rtc/pkg/rtsp/conn.go:664 +0x359
github.com/AlexxIT/go2rtc/cmd/rtsp.worker.func1({0xafd940, 0xc000280028})
        github.com/AlexxIT/go2rtc/cmd/rtsp/rtsp.go:181 +0x465
github.com/AlexxIT/go2rtc/pkg/streamer.(*Element).Fire(0x0, {0xafd940, 0xc000280028})
        github.com/AlexxIT/go2rtc/pkg/streamer/streamer.go:27 +0x47
github.com/AlexxIT/go2rtc/pkg/tcp.(*Server).Serve.func1()
        github.com/AlexxIT/go2rtc/pkg/tcp/server.go:28 +0x45
created by github.com/AlexxIT/go2rtc/pkg/tcp.(*Server).Serve
        github.com/AlexxIT/go2rtc/pkg/tcp/server.go:27 +0x29
    Last message repeated 3 timesge repeated 3 times
av_interleaved_write_frame(): Broken pipe
    Last message repeated 1 times
frame=18990 fps= 30 q=3.0 Lsize=N/A time=00:10:32.83 bitrate=N/A dup=9580 drop=0 speed=   1x
video:1624518kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!
```

**Comment by AlexxIT** [comment]
Not relevant today
