### ISSUE TITLE
Could not start go2rtc after HA upgrade

### ISSUE THREAD

**Issue by RobusX** [AlexxIT/go2rtc#596]
After HA upgrade from 2023.07.03 to 2023.08.03 I could not start go2rtc anymore (go2rtc always shuts down after start) and 
in the left slidebar menu is never started., not possible to config it.
Approximately at the same time I enabled rtsp stream on the EZivz cloud for each cam separately in the section "LAN view" (then i disabled it back,) but there was no difference. 
Cams (I have 5x Ezviz cams of C2C type) worked quite quite ok until now,  with no frequent usage because of high cpu consumption due to unsupported H.265 codec in the browsers (i could not set stream to H.264 with stream parameters change) and I did also not managed to enable HW decoder on my Synology 920+
I have in the HA folder go2rtc.yaml with debug logs enabled. The same error appears if only debug enabled logs are in go2rtcyaml, otherwise it is empty file.
I am using go2rtc together with WebRTC.
Logs below were found within go2rtc logs under addon section. HA has no logs in homeassistant.log about go2rtc errors.

192.168.2.20 is IP address of my homeassistant VM  (synology 920+).

Please give my some advice, what could be wrong and how i can solve this.
I could only try with go2rtc and webrtc deletion and install it again..but i doubt this will solve situation..
i do not know what else can be done. Thank you very much, Rob.

21:14:40.603 INF go2rtc version 1.6.2 linux/amd64
21:14:40.604 INF [api] listen addr=0.0.0.0:1984
21:14:40.605 INF [rtsp] listen addr=:8554
21:14:40.611 INF [webrtc] listen addr=:8555
21:14:40.615 DBG [hass] load config url=hass:Aqara-Hub-M1S-52C6
21:14:40.616 DBG [hass] load config url=hass:Aqara-Hub-M1S-61D3
21:14:40.616 DBG [hass] load config url=hass:Presence-Sensor-FP2-6822
21:14:40.617 INF [srtp] listen addr=0.0.0.0:8443
04:44:17.618 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="unsupported method: GET"
04:44:35.697 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: 0\f\x02\x01\x01`\a\x02\x01\x03\x04\x00�\x00"
04:44:50.769 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: 0\x1d\x02\x01\x01w\x18�\x161.3.6.1.4.1.1466.20037"
04:45:05.805 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: stats"
04:45:22.878 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: \x10�\v\x00LIOR<\x02\x00\x00����\x00\x00\x02\x00�XsUP���I���\x11�&�\a��CL9\x11�DE�x����N��\x1d\x10\x03\x00\x00ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
04:45:39.950 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: \x05\x00\v\x03\x10\x00\x00\x00H\x00\x00\x00\x01\x00\x00\x00�\x10�\x10\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x01\x00\b���\x1f]�\x11��\b\x00+\x14��\x03\x00\x00\x00\x04]���\x1c�\x11��\b\x00+\x10H`\x02\x00\x00\x00"
04:45:57.022 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: \x12\x01\x00\x1a\x00\x00\x00\x00\x00\x00\v\x00\x06\x01\x00\x11\x00\x01�\b\x00\x01U\x00\x00\x01"
04:46:12.109 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: �\x00\x00(5�"
04:46:29.181 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: \x00\x00\x00\t\x00\x03\x00\x00\x00"
04:46:44.253 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: \x03\x00\x00,'�\x00\x00\x00\x00\x00Cookie: mstshash=eltons"
04:46:59.324 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: *1"
04:47:16.398 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="read tcp 192.168.2.20:8554->87.136.106.77:49359: i/o timeout"
04:47:19.472 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: \x00\x00\x00n�SMB@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00$\x00\x04\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x02\x10\x02\x00\x03\x02\x03\x11\x03"
04:47:34.507 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="parse \"$\\xab0H(\\xda\\x04\\xb5\\xbb\\x17\\xb76\\xa0P}+ɵ\\x9e\\x8aV\\xb3\\x17a\\b渦}4\\x00\": net/url: invalid control character in URL"
21:14:11.061 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="read tcp 192.168.2.20:8554->172.105.112.139:39350: i/o timeout"
21:14:11.098 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: "
21:14:11.134 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="unsupported method: GET"
21:14:16.170 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="read tcp 192.168.2.20:8554->172.105.112.139:32768: i/o timeout"
21:14:21.191 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="read tcp 192.168.2.20:8554->172.105.112.139:32770: i/o timeout"
21:14:21.212 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="unsupported method: GET"
21:14:26.251 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="read tcp 192.168.2.20:8554->172.105.112.139:58302: i/o timeout"
21:14:31.293 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="read tcp 192.168.2.20:8554->172.105.112.139:58330: i/o timeout"
21:14:31.293 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="read tcp 192.168.2.20:8554->172.105.112.139:58316: i/o timeout"
21:14:31.293 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: \x0e\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00bbbb0100000001"
21:14:31.373 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="parse \"\\xfe{\\x0e\\x05\\xb0\\xcap\\x04\\xbc\\x8d\\x00\\xf2\\xf5\": net/url: invalid control character in URL"
21:14:31.409 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: \x16\x03\x01\x02\x00\x01\x00\x01�\x03\x03~�\x19r��&��r\x1c�_��b�@\bmy;����,xj��� \x11�\x00�V`�[ݤ�S~���W�ݚ����6S!Ih��\x10\x00�\x13\x02\x13\x03\x13\x01\x003\x009\x005\x00/�,�0\x00�\x00�̨̩̪���������]�a�W�S�+�/\x00�\x00����������\\�`�V�R�$�(\x00k\x00j�s�w\x00�\x00��#�'\x00g\x00@�r�v\x00�\x00��"
21:20:18.315 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="read tcp 192.168.2.20:8554->43.133.24.19:49264: read: connection reset by peer"
01:37:20.840 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="unsupported method: GET"
01:37:37.914 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: 0\f\x02\x01\x01`\a\x02\x01\x03\x04\x00�\x00"
01:37:52.985 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: 0\x1d\x02\x01\x01w\x18�\x161.3.6.1.4.1.1466.20037"
01:38:08.020 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: stats"
01:38:25.091 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: \x10�\v\x00LIOR<\x02\x00\x00����\x00\x00\x02\x00�XsUP���I���\x11�&�\a��CL9\x11�DE�x����N��\x1d\x10\x03\x00\x00ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ"
01:38:42.160 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: \x05\x00\v\x03\x10\x00\x00\x00H\x00\x00\x00\x01\x00\x00\x00�\x10�\x10\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x01\x00\b���\x1f]�\x11��\b\x00+\x14��\x03\x00\x00\x00\x04]���\x1c�\x11��\b\x00+\x10H`\x02\x00\x00\x00"
01:38:59.230 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: \x12\x01\x00\x1a\x00\x00\x00\x00\x00\x00\v\x00\x06\x01\x00\x11\x00\x01�\b\x00\x01U\x00\x00\x01"
01:39:16.342 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: �\x00\x00(ft�\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x01��\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
01:39:33.443 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: \x00\x00\x00\t\x00\x03\x00\x00\x00"
01:39:48.514 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: \x03\x00\x00,'�\x00\x00\x00\x00\x00Cookie: mstshash=eltons"
01:40:03.703 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: *1"
01:40:20.776 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="read tcp 192.168.2.20:8554->87.234.146.113:60547: i/o timeout"
01:40:23.846 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: \x00\x00\x00n�SMB@\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00$\x00\x04\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x02\x10\x02\x00\x03\x02\x03\x11\x03"
01:40:38.915 WRN github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 > error="wrong request: \x16\x03\x01\x00�\x01\x00\x00�\x03\x03�$����\x05�����\x7fM�k\x0e?C;m�<��$�#�c�V �\tG���y[᭩�:��T[E&%t�u����b�Co%\x002�+�/�,�0̨̩�\t�\x13�

**Comment by smartmatic** [comment]
I have also problems since the last HA Update. The Add-On does no longer start. Once i restart it it will immediately shutdown. I got those error log

`
09:37:02.904 INF go2rtc version 1.6.2 linux/arm64
09:37:02.906 INF [api] listen addr=0.0.0.0:1984
09:37:02.907 INF [rtsp] listen addr=0.0.0.0:8554
09:37:02.908 INF [webrtc] listen addr=0.0.0.0:8555/tcp
09:37:02.915 INF [srtp] listen addr=0.0.0.0:8443
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x53cc84]
goroutine 9 [running]:
net/rpc.(*Client).send(0x400042a008?, 0x0?)
	net/rpc/client.go:72 +0x24
net/rpc.(*Client).Go(0x40000bf708?, {0x7d1a3e, 0x1a}, {0x0?, 0x0}, {0x68e6a0?, 0x4000428060}, 0x40004100c0)
	net/rpc/client.go:315 +0x160
net/rpc.(*Client).Call(...)
	net/rpc/client.go:321
github.com/AlexxIT/go2rtc/pkg/roborock.(*Client).GetHomesecConnectStatus(0x4000220000)
	github.com/AlexxIT/go2rtc/pkg/roborock/client.go:208 +0x78
github.com/AlexxIT/go2rtc/pkg/roborock.(*Client).Connect(0x4000220000)
	github.com/AlexxIT/go2rtc/pkg/roborock/client.go:61 +0x4c
github.com/AlexxIT/go2rtc/internal/roborock.handle({0x400003a480, 0x87})
	github.com/AlexxIT/go2rtc/internal/roborock/roborock.go:23 +0x6c
github.com/AlexxIT/go2rtc/internal/streams.GetProducer({0x400003a480, 0x87})
	github.com/AlexxIT/go2rtc/internal/streams/handlers.go:40 +0x3c
github.com/AlexxIT/go2rtc/internal/streams.(*Producer).Dial(0x40001883f0)
	github.com/AlexxIT/go2rtc/internal/streams/producer.go:62 +0xd0
github.com/AlexxIT/go2rtc/internal/streams.(*Stream).AddConsumer(0x40001cc3c0, {0x8d8de0?, 0x40002d8b40})
	github.com/AlexxIT/go2rtc/internal/streams/stream.go:61 +0x490
github.com/AlexxIT/go2rtc/internal/rtsp.tcpHandler.func1({0x6affa0?, 0x8d23d8?})
	github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:189 +0x584
github.com/AlexxIT/go2rtc/pkg/core.(*Listener).Fire(...)
	github.com/AlexxIT/go2rtc/pkg/core/listener.go:16
github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Accept(0x40002d8b40)
	github.com/AlexxIT/go2rtc/pkg/rtsp/server.go:94 +0xa54
github.com/AlexxIT/go2rtc/internal/rtsp.tcpHandler(0x40002d8b40)
	github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:221 +0x198
created by github.com/AlexxIT/go2rtc/internal/rtsp.Init.func1
	github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:75 +0x3c
`

**Comment by AlexxIT** [comment]
@RobusX some of your software request go2rtc RTSP port like it is HTTP port

**Comment by AlexxIT** [comment]
Please let me know if the problem is relevant
