### ISSUE TITLE
Fix malformed HTTP version for HomeKit source

### ISSUE THREAD

**Issue by buchvald** [AlexxIT/go2rtc#620]
Hi

When i start go2rtc addon it will run for some seconds and the stop.

I get this in my log.

```
18:08:16.609 INF go2rtc version 1.7.0 linux/amd64
18:08:16.610 INF [api] listen addr=0.0.0.0:1984
18:08:16.610 INF [rtsp] listen addr=0.0.0.0:8554
18:08:16.611 INF [webrtc] listen addr=0.0.0.0:8555/tcp
18:08:21.705 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:21.820 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:21.962 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:22.100 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:22.210 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:22.322 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:22.440 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:22.584 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:22.717 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:22.999 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:23.149 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:23.254 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:23.350 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:23.459 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:23.571 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Entrecam
18:08:23.587 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:23.716 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:23.844 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:23.942 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:24.040 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:24.198 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:24.319 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:24.420 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:24.544 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:24.671 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:24.823 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:24.921 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:25.049 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:25.174 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:25.299 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:25.422 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:25.522 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:25.621 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:25.712 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Entrecam
18:08:25.733 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:25.896 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:26.005 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:26.119 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:26.220 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:26.324 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:26.470 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
18:08:26.581 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="malformed HTTP version \"{\\\"characteristics\\\":[{\\\"aid\\\":1,\\\"iid\\\":56,\\\"status\\\":-70410}]}HTTP/1.1\"" url=hass:Bryggerscam
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xa165b7]
goroutine 16 [running]:
github.com/AlexxIT/go2rtc/pkg/srtp.(*Server).DelSession(0xc0003226f0, 0x40df65?)
	github.com/AlexxIT/go2rtc/pkg/srtp/server.go:58 +0x57
github.com/AlexxIT/go2rtc/pkg/homekit.(*Client).Stop(0xc00020f1e0)
	github.com/AlexxIT/go2rtc/pkg/homekit/client.go:179 +0x71
github.com/AlexxIT/go2rtc/internal/streams.(*Producer).stop(0xc0001a02d0)
	github.com/AlexxIT/go2rtc/internal/streams/producer.go:260 +0x12f
github.com/AlexxIT/go2rtc/internal/streams.(*Stream).stopProducers(0xc00009b540)
	github.com/AlexxIT/go2rtc/internal/streams/stream.go:98 +0xcd
github.com/AlexxIT/go2rtc/internal/streams.(*Stream).RemoveConsumer(0xc00009b540, {0xcabb70, 0xc00034e160})
	github.com/AlexxIT/go2rtc/internal/streams/stream.go:63 +0x232
github.com/AlexxIT/go2rtc/internal/rtsp.tcpHandler.func1.1()
	github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:197 +0x25
github.com/AlexxIT/go2rtc/internal/rtsp.tcpHandler(0xc00034e160)
	github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:245 +0x328
created by github.com/AlexxIT/go2rtc/internal/rtsp.Init.func1 in goroutine 7
	github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:75 +0x45
```

**Comment by AlexxIT** [comment]
Looks like it's HomeKit camera. Show your config and camera model.

**Comment by buchvald** [comment]
Thank you for your respond.

Config:

_streams:
    entrecam: hass:Entrecam	
    bryggerscam: hass:Bryggerscam_


Both cameras are Aqara G2H.
They are connected via "HomeKit Device" in Home Assistant.

The setup has worked until now.

**Comment by AlexxIT** [comment]
Should be fixed in latest master version

**Comment by buchvald** [comment]
Thanks

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.7.1
