### ISSUE TITLE
Fix panic on aac.RTPDepay

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/go2rtc#635]
@AlexxIT I am trying to use a Vikylin PTZ-4825X-IS that has a really slow to start stream and ran across this issue, and I tried 1.7.1 so that I could use `#timeout=90`, and I think I might be getting the same panic that @itsolon is, it happens as soon as I try to view the stream where I used `#timeout=90`.

Here's the full error:

```
2023-09-11 19:38:58.387321835  [INFO] Starting go2rtc...
2023-09-11 19:38:58.507663094  19:38:58.507 INF go2rtc version 1.7.1 linux/amd64
2023-09-11 19:38:58.508052612  19:38:58.508 INF [api] listen addr=0.0.0.0:1984
2023-09-11 19:38:58.508656341  19:38:58.508 INF [rtsp] listen addr=0.0.0.0:8554
2023-09-11 19:38:58.508983978  19:38:58.508 INF [webrtc] listen addr=0.0.0.0:8555/tcp
2023-09-11 19:39:03.963023312  panic: runtime error: slice bounds out of range [:8192] with capacity 444
2023-09-11 19:39:03.963033718  
2023-09-11 19:39:03.963071783  goroutine 199 [running]:
2023-09-11 19:39:03.963077510  github.com/AlexxIT/go2rtc/pkg/mp4.(*Consumer).AddTrack.RTPDepay.func5(0xc0001d2d80)
2023-09-11 19:39:03.963101397  	github.com/AlexxIT/go2rtc/pkg/aac/rtp.go:24 +0x357
2023-09-11 19:39:03.963105658  github.com/AlexxIT/go2rtc/pkg/core.(*Sender).HandleRTP.func1()
2023-09-11 19:39:03.963127588  	github.com/AlexxIT/go2rtc/pkg/core/track.go:146 +0x9b
2023-09-11 19:39:03.963131919  created by github.com/AlexxIT/go2rtc/pkg/core.(*Sender).HandleRTP in goroutine 77
2023-09-11 19:39:03.963156713  	github.com/AlexxIT/go2rtc/pkg/core/track.go:140 +0x359
2023-09-11 19:39:03.972870302  [INFO] The go2rtc service exited with code 2 (by signal 0)
2023-09-11 19:39:04.985269822  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
```

Let me know if I can provide any more details :bow:

_Originally posted by @mattkasa in https://github.com/AlexxIT/go2rtc/issues/594#issuecomment-1714885466_

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.0
