### ISSUE TITLE
Panic on HLS consumer

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/go2rtc#718]
```
github.com/AlexxIT/go2rtc/internal/hls/hls.go:218 > error="write tcp 127.0.0.1:1984->127.0.0.1:38772: write: broken pipe"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x673b05]

goroutine 4197 [running]:
bufio.(*Writer).Flush(0xc001126080)
 bufio/bufio.go:642 +0x45
net/http.(*response).FlushError(0xc0001bc000)
 net/http/server.go:1718 +0x36
net/http.(*response).Flush(0x600?)
 net/http/server.go:1711 +0x13
github.com/AlexxIT/go2rtc/pkg/core.(*WriteBuffer).Write(0xc0022e8740, {0xc0002fac00?, 0xc00012ad80?, 0xc000a76eb0?})
 github.com/AlexxIT/go2rtc/pkg/core/writebuffer.go:37 +0x123
github.com/AlexxIT/go2rtc/pkg/mp4.(*Consumer).AddTrack.func3(0xc0000d8d90?)
 github.com/AlexxIT/go2rtc/pkg/mp4/consumer.go:120 +0xa5
github.com/AlexxIT/go2rtc/pkg/mp4.(*Consumer).AddTrack.RTPDepay.func5(0xc00012acf0)
 github.com/AlexxIT/go2rtc/pkg/aac/rtp.go:49 +0xb8
github.com/AlexxIT/go2rtc/pkg/core.(*Sender).HandleRTP.func1()
 github.com/AlexxIT/go2rtc/pkg/core/track.go:146 +0x9b
created by github.com/AlexxIT/go2rtc/pkg/core.(*Sender).HandleRTP in goroutine 4193
 github.com/AlexxIT/go2rtc/pkg/core/track.go:140 +0x359
 ```

**Comment by AlexxIT** [comment]
Once again
```
23:01:39.044 ERR github.com/AlexxIT/go2rtc/internal/hls/hls.go:218 > error="write tcp 127.0.0.1:1984->127.0.0.1:58388: write: broken pipe"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6754e1]

goroutine 1149 [running]:
bufio.(*Writer).Write(0xc000abe9c0, {0xc000417000?, 0x7f8398390108?, 0x20?})
 bufio/bufio.go:682 +0xe1
net/http.(*response).write(0xc0001b02a0, 0x2b13, {0xc000417000, 0x2b13, 0x2ea7}, {0x0, 0x0})
 net/http/server.go:1648 +0x22a
net/http.(*response).Write(0x2ea7?, {0xc000417000?, 0x0?, 0xc000417000?})
 net/http/server.go:1606 +0x2a
github.com/AlexxIT/go2rtc/pkg/core.(*WriteBuffer).Write(0xc000aac7c0, {0xc000417000?, 0xc00020af30?, 0xc000087eb8?})
 github.com/AlexxIT/go2rtc/pkg/core/writebuffer.go:33 +0x92
github.com/AlexxIT/go2rtc/pkg/mp4.(*Consumer).AddTrack.func1(0xc0002ce450?)
 github.com/AlexxIT/go2rtc/pkg/mp4/consumer.go:77 +0xae
github.com/AlexxIT/go2rtc/pkg/h264.RTPDepay.func1(0xc00020aea0)
 github.com/AlexxIT/go2rtc/pkg/h264/rtp.go:100 +0x345
github.com/AlexxIT/go2rtc/pkg/core.(*Sender).HandleRTP.func1()
 github.com/AlexxIT/go2rtc/pkg/core/track.go:144 +0x62
created by github.com/AlexxIT/go2rtc/pkg/core.(*Sender).HandleRTP in goroutine 1136
 github.com/AlexxIT/go2rtc/pkg/core/track.go:140 +0x359
```

**Comment by AlexxIT** [comment]
Probably fixed v1.7.0 https://github.com/AlexxIT/go2rtc/commit/2e4e75e386bdaaacbcefa51e399d849ec7534ddc
