### ISSUE TITLE
Fix homekit source panic on stop producer

### ISSUE THREAD

**Issue by seydx** [AlexxIT/go2rtc#734]
Hey @AlexxIT 

Any idea what could be causing this error?

```
[7.11.2023, 17:03:07] [go2rtc] DBG [exec] run url="exec:ffmpeg -hide_banner -v error -fflags nobuffer -flags low_delay -timeout 5000000 -user_agent go2rtc/ffmpeg -rtsp_transport tcp -i rtsp://127.0.0.1:8654/eingang_kamera_fullhd?audio -map 0:a:0? -c:a:0 aac -map 0:a:0? -c:a:1 libopus -application:a:1 lowdelay -frame_duration 20 -min_comp 0 -vn -user_agent ffmpeg/go2rtc -rtsp_transport tcp -f rtsp {output}"
[7.11.2023, 17:03:07] [go2rtc] DBG [rtsp] new consumer stream=eingang_kamera_fullhd
[7.11.2023, 17:03:09] [go2rtc] DBG [streams] start producer url=homekit://192.168.178.72:54019?client_id=XXXclient_private=XXX&device_id=XXX&device_public=XXX
[7.11.2023, 17:03:20] [go2rtc] Error demuxing input file 0: Operation timed out
[7.11.2023, 17:03:20] [go2rtc] rtsp://127.0.0.1:8654/eingang_kamera_fullhd?audio: Operation timed out
[7.11.2023, 17:03:20] [go2rtc] DBG [exec] run launch=12.395076875s
[7.11.2023, 17:03:20] [go2rtc] DBG [streams] stop producer url=ffmpeg:eingang_kamera_fullhd#audio=aac#audio=opus
[7.11.2023, 17:03:20] [go2rtc] ERR github.com/AlexxIT/go2rtc/internal/mjpeg/init.go:41 > error="streams: codecs not matched: AAC, OPUS => JPEG, H264, H265"
[7.11.2023, 17:03:20] [go2rtc] DBG [rtsp] handle=EOF
[7.11.2023, 17:03:20] [go2rtc] DBG [streams] stop producer url=homekit://192.168.178.72:54019?client_id=XXX&client_private=XXX&device_id=XXX&device_public=XXX
[7.11.2023, 17:03:20] [go2rtc] panic: runtime error: invalid memory address or nil pointer dereference
[7.11.2023, 17:03:20] [go2rtc] [signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1055cd080]
[7.11.2023, 17:03:20] [go2rtc] 
[7.11.2023, 17:03:20] [go2rtc] goroutine 37 [running]:
[7.11.2023, 17:03:20] [go2rtc] github.com/AlexxIT/go2rtc/pkg/srtp.(*Server).DelSession(0x140002893b0, 0x1400013e000?)
[7.11.2023, 17:03:20] [go2rtc]      github.com/AlexxIT/go2rtc/pkg/srtp/server.go:61 +0xd0
[7.11.2023, 17:03:20] [go2rtc] github.com/AlexxIT/go2rtc/pkg/homekit.(*Client).Stop(0x140000a2270)
[7.11.2023, 17:03:20] [go2rtc]      github.com/AlexxIT/go2rtc/pkg/homekit/client.go:179 +0x78
[7.11.2023, 17:03:20] [go2rtc] github.com/AlexxIT/go2rtc/internal/streams.(*Producer).stop(0x140000c0d80)
[7.11.2023, 17:03:20] [go2rtc]      github.com/AlexxIT/go2rtc/internal/streams/producer.go:260 +0x154
[7.11.2023, 17:03:20] [go2rtc] github.com/AlexxIT/go2rtc/internal/streams.(*Stream).stopProducers(0x140001fe580?)
[7.11.2023, 17:03:20] [go2rtc]      github.com/AlexxIT/go2rtc/internal/streams/stream.go:98 +0x10c
[7.11.2023, 17:03:20] [go2rtc] github.com/AlexxIT/go2rtc/internal/streams.(*Stream).RemoveConsumer(0x140001de580, {0x105887ff0, 0x140001fe580})
[7.11.2023, 17:03:20] [go2rtc]      github.com/AlexxIT/go2rtc/internal/streams/stream.go:63 +0x280
[7.11.2023, 17:03:20] [go2rtc] github.com/AlexxIT/go2rtc/internal/rtsp.tcpHandler.func1.1()
[7.11.2023, 17:03:20] [go2rtc]      github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:197 +0x2c
[7.11.2023, 17:03:20] [go2rtc] github.com/AlexxIT/go2rtc/internal/rtsp.tcpHandler(0x140001fe580)
[7.11.2023, 17:03:20] [go2rtc]      github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:245 +0x2ec
[7.11.2023, 17:03:20] [go2rtc] created by github.com/AlexxIT/go2rtc/internal/rtsp.Init.func1 in goroutine 7
[7.11.2023, 17:03:20] [go2rtc]      github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:75 +0x40
[7.11.2023, 17:03:20] The go2rtc process exited unexpectedly, will restart in 3 seconds...
[7.11.2023, 17:03:23] Restarting go2rtc...
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.8.3
