### ISSUE TITLE
wz_mini_hacks go2rtc enable homekit

### ISSUE THREAD

**Issue by tdashmike** [AlexxIT/go2rtc#766]
Hello,

I am trying to enable homekit on the wz_mini_hack firmware but discover does not seem to be working on Apple Home or Home Assistant. There are no errors in the go2rtc log.

```
log:
  level: debug # default level
  api: debug
  exec: debug
  ngrok: debug
  rtsp: debug
  streams: debug
  webrtc: debug
ffmpeg:
  bin: /opt/wz_mini/bin/ffmpeg
homekit:
  360p:                # same stream ID from streams list
    pin: 12345678         # custom PIN, default: 19550224
    name: Camera      # custom camera name, default: generated from stream ID
streams:
  1080p:
# NOTE: USE /dev/video6 for Wyze Cam v2/PanV1!
  - exec:ffmpeg -fflags +genpts+flush_packets+nobuffer+bitexact -flags +low_delay -thread_queue_size 100 -analyzeduration 50 -probesize 50 -pix_fmt yuv420p -r 30 -i /dev/video1  -flags +global_header -movflags +empty_moov+default_base_moof+frag_keyframe -framerate 30 -video_size 1920x1080 -pix_fmt yuv420p -c:v copy -copyts -rtsp_transport tcp -f rtsp {output}
  - exec:ffmpeg -hide_banner -f alsa -ac 1 -i dsnooper0 -c:a copy -muxdelay 0 -muxpreload 0 -f rtsp {output}
  - exec:ffmpeg -hide_banner -f alsa -ac 1 -i dsnooper0 -c:a libfdk_aac -afterburner 1 -channels 1 -b:a 128k -profile:a aac_he -ar 16000 -strict experimental -muxdelay 0 -muxpreload 0 -ac:a 1 -f rtsp {output}
# libopus has higher cpu requirements, audio may studder.
  - exec:ffmpeg -hide_banner -f alsa -ac 1 -i dsnooper0 -c:a libopus -muxdelay 0 -muxpreload 0 -ac:a 1 -af adelay=0|0 -f rtsp {output}
  360p:
# NOTE: USE /dev/video7 for Wyze Cam v2/PanV1!
  - exec:ffmpeg -fflags +genpts+flush_packets+nobuffer+bitexact -flags +low_delay -thread_queue_size 100 -analyzeduration 50 -probesize 50 -pix_fmt yuv420p -r 30 -i /dev/video2 -framerate 30 -video_size 640x360 -pix_fmt yuv420p -c:v copy -copyts -rtsp_transport tcp -f rtsp {output}
  - exec:ffmpeg -hide_banner -f alsa -ac 1 -i dsnooper2 -c:a copy -muxdelay 0 -muxpreload 0 -ac:a 1 -f rtsp {output}
  - exec:ffmpeg -hide_banner -f alsa -ac 1 -i dsnooper2 -c:a libfdk_aac -afterburner 1 -channels 1 -b:a 128k -profile:a aac_he -ar 16000 -strict experimental -muxdelay 0 -muxpreload 0 -ac:a 1 -f rtsp {output}
# libopus has higher cpu requirements, audio may studder.
  - exec:ffmpeg -hide_banner -f alsa -ac 1 -i dsnooper2 -c:a libopus -muxdelay 0 -muxpreload 0 -ac:a 1 -af adelay=0|0 -f rtsp {output}

```

**Comment by AlexxIT** [comment]
Go2rtc version?

**Comment by tdashmike** [comment]
`^[[90m03:32:36.690^[[0m ^[[32mINF^[[0m go2rtc version 1.8.0 linux/mipsle`

After a while one of the cameras finally showed up in HASS but I am getting this error: An unhandled error occurred while attempting to pair with this device. This may be a temporary failure or your device may not be supported currently: M2: Accessory did not send public key

```
Logger: homeassistant.components.homekit_controller.config_flow
Source: components/homekit_controller/config_flow.py:492
Integration: HomeKit Device ([documentation](https://www.home-assistant.io/integrations/homekit_controller), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+homekit_controller%22))
First occurred: 10:26:40 PM (11 occurrences)
Last logged: 11:12:46 PM

Pairing attempt failed with an unhandled exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 492, in async_step_pair
    self.finish_pairing = await discovery.async_start_pairing(self.hkid)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/controller/ip/discovery.py", line 67, in async_start_pairing
    request, expected = state_machine.send(response)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohomekit/protocol/__init__.py", line 135, in perform_pair_setup_part1
    raise InvalidError("M2: Accessory did not send public key")
aiohomekit.exceptions.InvalidError: M2: Accessory did not send public key
```

**Comment by AlexxIT** [comment]
I'm not sure if Hass can support HomeKit from go2rtc. Hass has not best HomeKit realisation.

**Comment by AlexxIT** [comment]
Please let me know if the problem is relevant
