### ISSUE TITLE
panic on pcm.RepackBackchannel

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/go2rtc#787]
```
2023-11-25 12:37:28.547592104  panic: runtime error: slice bounds out of range [1024:192]
2023-11-25 12:37:28.547600229
2023-11-25 12:37:28.547603438  goroutine 689 [running]:
2023-11-25 12:37:28.547606609  github.com/AlexxIT/go2rtc/pkg/pcm.RepackBackchannel.func1(0xc0000cd030)
2023-11-25 12:37:28.547609422      github.com/AlexxIT/go2rtc/pkg/pcm/helpers.go:32 +0x1de
2023-11-25 12:37:28.547617996  github.com/AlexxIT/go2rtc/pkg/core.(Sender).HandleRTP.func1()
2023-11-25 12:37:28.547623159      github.com/AlexxIT/go2rtc/pkg/core/track.go:137 +0xaa
2023-11-25 12:37:28.547626642  created by github.com/AlexxIT/go2rtc/pkg/core.(Sender).HandleRTP
2023-11-25 12:37:28.547691787      github.com/AlexxIT/go2rtc/pkg/core/track.go:131 +0x351
2023-11-25 12:37:28.558951515  [INFO] The go2rtc service exited with code 2 (by signal 0)
2023-11-25 12:37:29.567536123  [WARN] Using go2rtc binary from '/config/go2rtc' instead of the embedded one
2023-11-25 12:37:29.567543363  [INFO] Starting go2rtc...
```

**Comment by AlexxIT** [comment]
Some outdated go2rtc version. Not relevant any more.
