### ISSUE TITLE
HomeKit: Unable to add accessory. An unknown error occurred

### ISSUE THREAD

**Issue by idjul** [AlexxIT/go2rtc#874]
Hi, i have an issue when i. try to add my camera to HomeKit : Unable to add accessory. An unknown error occurred

```
streams:
  salon: 
    - rtsp://admin:password@192.168.1.50:554/live1.sdp
    - ffmpeg:salon#audio=opus
homekit:
  salon:
    pin: 58543600
    name: Salon
```

I don't think i did something wrong, i can see the camera when i try to add it in HomeKit, and there's nothing in the logs.

**Comment by Chrischi-** [comment]
Try downgrading to 1.8.2. 

All versions after 1.8.2 have the same behaviour for me. Even cameras that are already paired and work with 1.8.2.

Something may have been changed after 1.8.2. In the log (debug/trace) there are no hints or messages at all.

Maybe @AlexxIT  can help here.

Until then I have to stay with 1.8.2.

**Comment by AlexxIT** [comment]
Show screenshot with this error

**Comment by idjul** [comment]
> Try downgrading to 1.8.2.
> 
> All versions after 1.8.2 have the same behaviour for me. Even cameras that are already paired and work with 1.8.2.
> 
> Something may have been changed after 1.8.2. In the log (debug/trace) there are no hints or messages at all.
> 
> Maybe @AlexxIT can help here.
> 
> Until then I have to stay with 1.8.2.

@Chrischi- Latest version installed outside HA works well, the issue is inside HA, and we can't downgrade within HA.

@AlexxIT There's no logs related to homekit, nothing. Screenshot of the failure to pair the camera to HomeKit:

![IMG_84C798188093-1](https://github.com/AlexxIT/go2rtc/assets/36371545/e2c6cdb9-3a3e-4ea1-8cc7-24e02335b9fe)

**Comment by MercianWhitey** [comment]
Same issue here, using go2rtc with Frigate in a docker container. I've also degraded to 1.8.2 as suggested here and this does work.

**Comment by NickM-27** [comment]
@MercianWhitey you need to run frigate in host networking mode

**Comment by MercianWhitey** [comment]
I do have my docker network mode set to host. Without this, HomeKit doesn't even see the camera on the network. As I said, I have it working with 1.8.2 just not the latest.

Thanks

**Comment by cms365** [comment]
Same issue here when running v1.8.5 inside Home Assistant.

**Comment by SashaBusinaro** [comment]
I have the same problem with 1.9.0 and aqara camera

**Comment by SashaBusinaro** [comment]
I noticed that the problem only occurs when cameras are imported from homeassistant and not when they are connected directly through homekit.
Connecting it with - homekit:... works,
but not with - hass:...

**Comment by adifelice-godaddy** [comment]
I'm not sure if my setup is correct, but this is the error in Home Assistant when I try to pair it to Homekit Device:
```python3
2024-05-05 09:47:37.145 ERROR (MainThread) [homeassistant.components.homekit_controller.config_flow] Pairing attempt failed with an unhandled exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 491, in async_step_pair
    self.finish_pairing = await discovery.async_start_pairing(self.hkid)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohomekit/controller/ip/discovery.py", line 69, in async_start_pairing
    request, expected = state_machine.send(response)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohomekit/protocol/__init__.py", line 135, in perform_pair_setup_part1
    raise InvalidError("M2: Accessory did not send public key")
aiohomekit.exceptions.InvalidError: M2: Accessory did not send public key
```

**Comment by AlexxIT** [comment]
If Hass can't pair some HomeKit device - it's Hass problem. You should create your issue there.

If your trying to add go2rtc homekit camera to Hass - this is make no sense and not supported.

**Comment by adifelice-godaddy** [comment]
> If Hass can't pair some HomeKit device - it's Hass problem. You should create your issue there.
> 
> If your trying to add go2rtc homekit camera to Hass - this is make no sense and not supported.

Yes. I was adding the same camera again in HA Homekit, which made no sense. Adding it to Home App worked. I added an [update](https://github.com/AlexxIT/go2rtc/issues/874#issuecomment-2094838476).

**Comment by piwi3910** [comment]
Hi it's not a HASS issue. As the same issue exists when just using it as a homekit proxy.
My HASS is on another box then my Go2RTC (HA yellow) and my GO2RTC is on my NAS box that also runs my Frigate for resources as well as the USB being only USB2 and giving issues with my coral.

I've connected my Aqara doorbell via homekit to GO2RTC. not to HASS

![image](https://github.com/AlexxIT/go2rtc/assets/12539757/578d8786-98b6-4ee0-b214-ef57f79c0277)

I've done re-exposed it as a homekit device and i can see the device on all my phones, HASS and so on.

![image](https://github.com/AlexxIT/go2rtc/assets/12539757/b25fc438-8885-4e15-a29a-a53d2c6f457e)

However i cannot add the device anywhere:

![image](https://github.com/AlexxIT/go2rtc/assets/12539757/c2e0b788-3067-4edc-87e7-6995647c6dcd)

The camera stream works totally fine via the Frigate Custom integration. But i was hoping with re-exposing the camera i would get the the other entities part of the doorbell back to HASS.

**Comment by SteampowerJake** [comment]
I'm having the same issues with an Aqara doorbell. Stream works great in HA but can't get it to pair back to HomeKit, get the same M2 didn't send public key message. In the log I see this, 100% possible that it's a problem with my config:

[app] read config error=yaml: unmarshal errors:
line 11: cannot unmarshal !!str `front_door` into struct { Pin string "json:\"pin\""; Name string "json:\"name\""; DeviceID string "json:\"device_id\""; DevicePrivate string "json:\"device_private\""; Pairings []string "json:\"pairings\"" }
line 13: cannot unmarshal !!str `FrontDoor` into struct { Pin string "json:\"pin\""; Name string "json:\"name\""; DeviceID string "json:\"device_id\""; DevicePrivate string "json:\"device_private\""; Pairings []string "json:\"pairings\"" }
line 14: cannot unmarshal !!int `17362463` into struct { Pin string "json:\"pin\""; Name string "json:\"name\""; DeviceID string "json:\"device_id\""; DevicePrivate string "json:\"device_private\""; Pairings []string "json:\"pairings\"" }
line 15: cannot unmarshal !!str `front_door` into struct { Pin string "json:\"pin\""; Name string "json:\"name\""; DeviceID string "json:\"device_id\""; DevicePrivate string "json:\"device_private\""; Pairings []string "json:\"pairings\"" }

**Comment by AlexxIT** [comment]
`yaml: unmarshal errors` means you have the wrong config format.

**Comment by SteampowerJake** [comment]
Figured, thank you!

**Comment by gewaechshaus** [comment]
Hey,

let me say big thanks to @AlexxIT making the add-on available to us. To introduce myself, my name is Jan and I just joined the HASS thing 2 weeks ago (migrated from homebridge). I am kind of experienced in terms of development and administration, but not in case of python, go script etc. 

I am running into the same issue with a minimal and new setup:

<img width="379" alt="Bildschirmfoto 2024-11-25 um 08 05 53" src="https://github.com/user-attachments/assets/e1e62e37-8caa-4183-a916-c483af6df441">

---
Installed go2rtc as Addon, **v1.9.7**
<img width="475" alt="Bildschirmfoto 2024-11-25 um 08 12 23" src="https://github.com/user-attachments/assets/39ea83de-276d-499d-8a70-89a05b88adeb">
---
```
streams:
 dev:
  - rtsp://my:credentials@192.168.178.XXX/live0
  - ffmpeg:dev#video=h264#hardware  # if your camera doesn't support H264, important for HomeKit
  - ffmpeg:dev#audio=opus           # only OPUS audio supported by HomeKit

homekit:
 dev:                   # same stream ID from streams list
  pin: 10101010         # custom PIN, default: 19550224
  name: Debug.          # custom camera name, default: generated from stream ID
  device_id: dev       	# custom ID, default: generated from stream ID
  device_private: dev  	# custom key, default: generated from stream ID
```
---
<img width="1240" alt="Bildschirmfoto 2024-11-25 um 08 06 27" src="https://github.com/user-attachments/assets/9ca54011-6a43-4cc6-a418-87684d1e9ded">

---

![IMG_7126](https://github.com/user-attachments/assets/7c54ae99-5131-44b8-ae09-0b716858e374)


Cheers
Jan

**Comment by AlexxIT** [comment]
@gewaechshaus Have you shown your entire go2rtc config? There's nothing else in it?

**Comment by AlexxIT** [comment]
If that's all the customization is - I don't see any error in it. And I don't know any reason why it might not work.
Common errors are:
- closed docker ports
- setting password on API module
- adding homekit camera from go2rtc to HA

**Comment by AlexxIT** [comment]
The docker IP is definitely wrong. Can you send a diagnostic of any of your integrations from HA? It will have useful information about your installation. I will test the same situation on my Raspberry + HassOS.

- go2rtc addon on HassOS haven't any problems with open ports
- by default API password disabled
- yes, it's the Apple founder's birthday

**Comment by piwi3910** [comment]
I changed it to use host networking, and that fixed the problem for me




Internal Use - Confidential

**Comment by AlexxIT** [comment]
"host networking" it's fix for "closed docker ports".
All my config examples has network host - https://hub.docker.com/r/alexxit/go2rtc
Hass addons also has network host.

But not everyone follows the documentation.

**Comment by AlexxIT** [comment]
WebRTC integration also run go2rtc inside container with network host option.
Many integrations has diagnostic feature https://www.home-assistant.io/integrations/diagnostics/

**Comment by gewaechshaus** [comment]
@AlexxIT - it's related to the eufy implementation and the way they use go2rtc / webrtc... I saw it in the scrypted logs, they are noisy so I stumbled upon some strange things. I have to trace this down a bit further.

**Comment by blackie333** [comment]
Have the same problem to add auto-dicovered go2rtc-266B (Aqara G4 Camera) to HomeKit integration on HassOS installation.
go2rtc log is following:
![image](https://github.com/user-attachments/assets/37ced234-3eee-42bc-9ff0-9ccf3dd0b731)

**Comment by gewaechshaus** [comment]
@blackie333 - indeed it looks like the same underlaying problem...

**Comment by ventrebleu** [comment]
Hey all, and thanks, @AlexxIT, for this awesome work!

I'm in the same boat:
- Installed go2rtc as an add-on (version 1.9.8)
- Using it to get my Nest doorbell (battery) to appear in Homekit (and potentially use its Secure Video feature)
- The stream works, I can see it in the go2rtc webUI
- HA discovers the new Homekit camera but I can't add it because of the `M2: Accessory did not send public key` error
- The go2rtc logs give me an error: `[homekit] unknown host: 172.30.32.1`

Has anybody figured it out?
Thanks!

**Comment by danielk117** [comment]
Same here. 

My setup: HASS and go2rtc as docker, network mode host, booth on the same host.

Added my Aqara G4 doorbell to go2rtc and republished it, using go2rtc.

```
streams:
  front_door:
    - homekit://192.168.170.178:40743?device_id=XXXX&device_public=XXXX&client_id=XXXX&client_private=XXXX
    - ffmpeg:front_door#audio=opus

homekit:
  front_door:
    pin: 12345678
    name: AqaraG4
```

Adding new device to HASS gave me `M2: Accessory did not send public key` error. go2rtc log show this:

```
01:25:03,780	trace	[api] POST /pair-setup 192.168.170.254:52788
01:25:03,780	error	[homekit] unknown host: 192.168.170.254
```

If I try to add the device to Apple Home instead, everthing is working fine.

**Comment by AlexxIT** [comment]
Some of the problems described in this issue should be fixed in the latest master version.

**Comment by danielk117** [comment]
Ok, I've switched to the `master` tag. It fails with a different message now.

go2rtc:

```
12:41:08,048	trace	[api] POST /pair-setup 192.168.170.254:58048
12:41:08,048	error	[homekit] unknown host: 192.168.170.254
```

home assistant:

```python
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 478, in async_step_pair
    self.finish_pairing = await discovery.async_start_pairing(self.hkid)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohomekit/controller/ip/discovery.py", line 68, in async_start_pairing
    request, expected = state_machine.send(response)
                        ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohomekit/protocol/__init__.py", line 132, in perform_pair_setup_part1
    handle_state_step(response_tlv, TLV.M2)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohomekit/protocol/__init__.py", line 90, in handle_state_step
    error_handler(tlv_dict[TLV.kTLVType_Error], f"step {expected_state}")
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohomekit/protocol/__init__.py", line 66, in error_handler
    raise BackoffError(stage)
aiohomekit.exceptions.BackoffError: step bytearray(b'\x02')
```

**Comment by AlexxIT** [comment]
Yeah, now the error is right - back off.

Because you don't need to add HomeKit cameras from go2rtc to Home Assistant. That doesn't make sense.
Open source, such as Home Assistant, do not implement the HomeKit protocol correctly.
