### ISSUE TITLE
Panic: concurrent write in the webrtc source

### ISSUE THREAD

**Issue by AlexxIT** [AlexxIT/go2rtc#935]
```
[go2rtc] DBG [rtsp] new consumer stream=xxx
[go2rtc] panic: concurrent write to websocket connection
[go2rtc] 
[go2rtc] goroutine 418 [running]:
[go2rtc] github.com/gorilla/websocket.(*messageWriter).flushFrame(0x14000030690, 0x1, {0x0?, 0x0?, 0x0?})
[go2rtc]     github.com/gorilla/websocket@v1.5.1/conn.go:632 +0x460
[go2rtc] github.com/gorilla/websocket.(*messageWriter).Close(0x1400054d6b8?)
[go2rtc]     github.com/gorilla/websocket@v1.5.1/conn.go:746 +0x48
[go2rtc] github.com/gorilla/websocket.(*Conn).WriteJSON(0x14000457500?, {0x1056435a0, 0x1400049d900})
[go2rtc]     github.com/gorilla/websocket@v1.5.1/json.go:29 +0x9c
[go2rtc] github.com/AlexxIT/go2rtc/internal/webrtc.go2rtcClient({0x1400018c827?, 0x44?})
[go2rtc]     github.com/AlexxIT/go2rtc/internal/webrtc/client.go:119 +0x37c
[go2rtc] github.com/AlexxIT/go2rtc/internal/webrtc.streamsHandler({0x1400018c820, 0x4b})
[go2rtc]     github.com/AlexxIT/go2rtc/internal/webrtc/client.go:47 +0x258
[go2rtc] github.com/AlexxIT/go2rtc/internal/streams.GetProducer({0x1400018c820, 0x4b})
[go2rtc]     github.com/AlexxIT/go2rtc/internal/streams/handlers.go:49 +0xc4
[go2rtc] github.com/AlexxIT/go2rtc/internal/streams.(*Producer).Dial(0x140001bc3f0)
[go2rtc]     github.com/AlexxIT/go2rtc/internal/streams/producer.go:62 +0xd0
[go2rtc] github.com/AlexxIT/go2rtc/internal/streams.(*Stream).AddConsumer(0x1400020a040, {0x10571a078?, 0x14000232000})
[go2rtc]     github.com/AlexxIT/go2rtc/internal/streams/add_consumer.go:26 +0x4a8
[go2rtc] github.com/AlexxIT/go2rtc/internal/rtsp.tcpHandler.func1({0x1055ffb80?, 0x1057138f0?})
[go2rtc]     github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:191 +0x54c
[go2rtc] github.com/AlexxIT/go2rtc/pkg/core.(*Listener).Fire(...)
[go2rtc]     github.com/AlexxIT/go2rtc/pkg/core/listener.go:16
[go2rtc] github.com/AlexxIT/go2rtc/pkg/rtsp.(*Conn).Accept(0x14000232000)
[go2rtc]     github.com/AlexxIT/go2rtc/pkg/rtsp/server.go:97 +0xa88
[go2rtc] github.com/AlexxIT/go2rtc/internal/rtsp.tcpHandler(0x14000232000)
[go2rtc]     github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:223 +0x17c
[go2rtc] created by github.com/AlexxIT/go2rtc/internal/rtsp.Init.func1 in goroutine 19
[go2rtc]     github.com/AlexxIT/go2rtc/internal/rtsp/rtsp.go:75 +0x40
[go2rtc] rtsp://127.0.0.1:8554/xxx?video&audio: Invalid data found when processing input
```

```yaml
streams:
  xxx: webrtc:ws://localhost:xxx/api/streams/xxx
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.0
