### ISSUE TITLE
WebRTC WriteRTP panic

### ISSUE THREAD

**Issue by ridderr** [AlexxIT/go2rtc#994]
Hi just noticed go2rtc stopped with below error
```
15:04:54.074 INF go2rtc version 1.8.5 linux/arm64
15:04:54.080 INF [rtsp] listen addr=:8554
15:04:54.080 INF [api] listen addr=:1984
15:04:54.083 INF [webrtc] listen addr=:8555
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x573644]

goroutine 10332 [running]:
github.com/AlexxIT/go2rtc/pkg/webrtc.(*Track).WriteRTP(0x4001b725a0, 0x66, 0x4001342b40)
	github.com/AlexxIT/go2rtc/pkg/webrtc/track.go:71 +0xb4
github.com/AlexxIT/go2rtc/pkg/webrtc.(*Conn).AddTrack.func1(0x4001342b40)
	github.com/AlexxIT/go2rtc/pkg/webrtc/consumer.go:47 +0xac
github.com/AlexxIT/go2rtc/pkg/h264.RTPPay.func1(0x400118f950)
	github.com/AlexxIT/go2rtc/pkg/h264/rtp.go:131 +0xc0
github.com/AlexxIT/go2rtc/pkg/h264.RTPDepay.func1(0x4002205b00)
	github.com/AlexxIT/go2rtc/pkg/h264/rtp.go:100 +0x324
github.com/AlexxIT/go2rtc/pkg/core.(*Sender).HandleRTP.func1()
	github.com/AlexxIT/go2rtc/pkg/core/track.go:147 +0x64
created by github.com/AlexxIT/go2rtc/pkg/core.(*Sender).HandleRTP in goroutine 10342
	github.com/AlexxIT/go2rtc/pkg/core/track.go:143 +0x424
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/go2rtc/releases/tag/v1.9.0
